// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: todo/v1/todo_service.proto

package todov1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTodoRequest struct {
	state               protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Todo     *CreateTodoRequest_Todo       `protobuf:"bytes,1,opt,name=todo,proto3"`
	xxx_hidden_SubTasks *[]*CreateTodoRequest_SubTask `protobuf:"bytes,2,rep,name=sub_tasks,json=subTasks,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTodoRequest) GetTodo() *CreateTodoRequest_Todo {
	if x != nil {
		return x.xxx_hidden_Todo
	}
	return nil
}

func (x *CreateTodoRequest) GetSubTasks() []*CreateTodoRequest_SubTask {
	if x != nil {
		if x.xxx_hidden_SubTasks != nil {
			return *x.xxx_hidden_SubTasks
		}
	}
	return nil
}

func (x *CreateTodoRequest) SetTodo(v *CreateTodoRequest_Todo) {
	x.xxx_hidden_Todo = v
}

func (x *CreateTodoRequest) SetSubTasks(v []*CreateTodoRequest_SubTask) {
	x.xxx_hidden_SubTasks = &v
}

func (x *CreateTodoRequest) HasTodo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Todo != nil
}

func (x *CreateTodoRequest) ClearTodo() {
	x.xxx_hidden_Todo = nil
}

type CreateTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Todo     *CreateTodoRequest_Todo
	SubTasks []*CreateTodoRequest_SubTask
}

func (b0 CreateTodoRequest_builder) Build() *CreateTodoRequest {
	m0 := &CreateTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todo = b.Todo
	x.xxx_hidden_SubTasks = &b.SubTasks
	return m0
}

// Request message for GetTodo
type GetTodoRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_ShowDeleted bool                   `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTodoRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *GetTodoRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *GetTodoRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *GetTodoRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetTodoRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetTodoRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ShowDeleted = false
}

type GetTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
	// default to true if not set
	ShowDeleted *bool
}

func (b0 GetTodoRequest_builder) Build() *GetTodoRequest {
	m0 := &GetTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

// Request message for ListTodos
type ListTodosRequest struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_PageSize    int32                        `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3"`
	xxx_hidden_PageToken   string                       `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3"`
	xxx_hidden_UserId      int64                        `protobuf:"varint,3,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Filter      *ListTodosRequest_Filter     `protobuf:"bytes,4,opt,name=filter,proto3,oneof"`
	xxx_hidden_OrderBy     *[]*ListTodosRequest_OrderBy `protobuf:"bytes,5,rep,name=order_by,json=orderBy,proto3"`
	xxx_hidden_ShowDeleted bool                         `protobuf:"varint,6,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ListTodosRequest) GetPageToken() string {
	if x != nil {
		return x.xxx_hidden_PageToken
	}
	return ""
}

func (x *ListTodosRequest) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *ListTodosRequest) GetFilter() *ListTodosRequest_Filter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *ListTodosRequest) GetOrderBy() []*ListTodosRequest_OrderBy {
	if x != nil {
		if x.xxx_hidden_OrderBy != nil {
			return *x.xxx_hidden_OrderBy
		}
	}
	return nil
}

func (x *ListTodosRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *ListTodosRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
}

func (x *ListTodosRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = v
}

func (x *ListTodosRequest) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *ListTodosRequest) SetFilter(v *ListTodosRequest_Filter) {
	x.xxx_hidden_Filter = v
}

func (x *ListTodosRequest) SetOrderBy(v []*ListTodosRequest_OrderBy) {
	x.xxx_hidden_OrderBy = &v
}

func (x *ListTodosRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ListTodosRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *ListTodosRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ListTodosRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *ListTodosRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ShowDeleted = false
}

type ListTodosRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The maximum number of todos to return
	// The service may return fewer than this value
	// If unspecified, defaults to 50
	// Maximum value is 1000
	PageSize int32
	// Page token received from a previous ListTodos call
	// Provide this to retrieve the next page
	PageToken string
	// parent
	UserId int64
	// Filter expression for todos
	// Examples: "status=PENDING", "assignee=user123"
	Filter *ListTodosRequest_Filter
	// Field to sort by
	// Examples: "created_at", "due_date", "priority"
	OrderBy []*ListTodosRequest_OrderBy
	// default to false if not set
	ShowDeleted *bool
}

func (b0 ListTodosRequest_builder) Build() *ListTodosRequest {
	m0 := &ListTodosRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PageSize = b.PageSize
	x.xxx_hidden_PageToken = b.PageToken
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_OrderBy = &b.OrderBy
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

// Response message for ListTodos
type ListTodosResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Todos         *[]*TodoModel          `protobuf:"bytes,1,rep,name=todos,proto3"`
	xxx_hidden_NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3"`
	xxx_hidden_TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosResponse) GetTodos() []*TodoModel {
	if x != nil {
		if x.xxx_hidden_Todos != nil {
			return *x.xxx_hidden_Todos
		}
	}
	return nil
}

func (x *ListTodosResponse) GetNextPageToken() string {
	if x != nil {
		return x.xxx_hidden_NextPageToken
	}
	return ""
}

func (x *ListTodosResponse) GetTotalSize() int32 {
	if x != nil {
		return x.xxx_hidden_TotalSize
	}
	return 0
}

func (x *ListTodosResponse) SetTodos(v []*TodoModel) {
	x.xxx_hidden_Todos = &v
}

func (x *ListTodosResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = v
}

func (x *ListTodosResponse) SetTotalSize(v int32) {
	x.xxx_hidden_TotalSize = v
}

type ListTodosResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The list of todos
	Todos []*TodoModel
	// Token to retrieve the next page of results
	// Empty if there are no more results
	NextPageToken string
	// Total count of todos matching the filter
	TotalSize int32
}

func (b0 ListTodosResponse_builder) Build() *ListTodosResponse {
	m0 := &ListTodosResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todos = &b.Todos
	x.xxx_hidden_NextPageToken = b.NextPageToken
	x.xxx_hidden_TotalSize = b.TotalSize
	return m0
}

// Request message for UpdateTodo
type UpdateTodoRequest struct {
	state                        protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_Todo              *UpdateTodoRequest_Todo                `protobuf:"bytes,1,opt,name=todo,proto3"`
	xxx_hidden_SubTaskOperations *[]*UpdateTodoRequest_SubTaskOperation `protobuf:"bytes,2,rep,name=sub_task_operations,json=subTaskOperations,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest) GetTodo() *UpdateTodoRequest_Todo {
	if x != nil {
		return x.xxx_hidden_Todo
	}
	return nil
}

func (x *UpdateTodoRequest) GetSubTaskOperations() []*UpdateTodoRequest_SubTaskOperation {
	if x != nil {
		if x.xxx_hidden_SubTaskOperations != nil {
			return *x.xxx_hidden_SubTaskOperations
		}
	}
	return nil
}

func (x *UpdateTodoRequest) SetTodo(v *UpdateTodoRequest_Todo) {
	x.xxx_hidden_Todo = v
}

func (x *UpdateTodoRequest) SetSubTaskOperations(v []*UpdateTodoRequest_SubTaskOperation) {
	x.xxx_hidden_SubTaskOperations = &v
}

func (x *UpdateTodoRequest) HasTodo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Todo != nil
}

func (x *UpdateTodoRequest) ClearTodo() {
	x.xxx_hidden_Todo = nil
}

type UpdateTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Todo              *UpdateTodoRequest_Todo
	SubTaskOperations []*UpdateTodoRequest_SubTaskOperation
}

func (b0 UpdateTodoRequest_builder) Build() *UpdateTodoRequest {
	m0 := &UpdateTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todo = b.Todo
	x.xxx_hidden_SubTaskOperations = &b.SubTaskOperations
	return m0
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteTodoRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteTodoRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteTodoRequest_builder) Build() *DeleteTodoRequest {
	m0 := &DeleteTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type BatchGetTodosRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ids         []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3"`
	xxx_hidden_ShowDeleted bool                   `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatchGetTodosRequest) Reset() {
	*x = BatchGetTodosRequest{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTodosRequest) ProtoMessage() {}

func (x *BatchGetTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchGetTodosRequest) GetIds() []int64 {
	if x != nil {
		return x.xxx_hidden_Ids
	}
	return nil
}

func (x *BatchGetTodosRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *BatchGetTodosRequest) SetIds(v []int64) {
	x.xxx_hidden_Ids = v
}

func (x *BatchGetTodosRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *BatchGetTodosRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BatchGetTodosRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ShowDeleted = false
}

type BatchGetTodosRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ids []int64
	// default to true if not set
	ShowDeleted *bool
}

func (b0 BatchGetTodosRequest_builder) Build() *BatchGetTodosRequest {
	m0 := &BatchGetTodosRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ids = b.Ids
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

type BatchGetTodosResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Todos *[]*TodoModel          `protobuf:"bytes,1,rep,name=todos,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchGetTodosResponse) Reset() {
	*x = BatchGetTodosResponse{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTodosResponse) ProtoMessage() {}

func (x *BatchGetTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchGetTodosResponse) GetTodos() []*TodoModel {
	if x != nil {
		if x.xxx_hidden_Todos != nil {
			return *x.xxx_hidden_Todos
		}
	}
	return nil
}

func (x *BatchGetTodosResponse) SetTodos(v []*TodoModel) {
	x.xxx_hidden_Todos = &v
}

type BatchGetTodosResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Todos []*TodoModel
}

func (b0 BatchGetTodosResponse_builder) Build() *BatchGetTodosResponse {
	m0 := &BatchGetTodosResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todos = &b.Todos
	return m0
}

type CreateTodoRequest_Todo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Title       string                 `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
	xxx_hidden_State       TodoModel_State        `protobuf:"varint,4,opt,name=state,proto3,enum=todo.v1.TodoModel_State,oneof"`
	xxx_hidden_Priority    TodoModel_Priority     `protobuf:"varint,5,opt,name=priority,proto3,enum=todo.v1.TodoModel_Priority,oneof"`
	xxx_hidden_Assignee    int64                  `protobuf:"varint,6,opt,name=assignee,proto3,oneof"`
	xxx_hidden_DueDate     *date.Date             `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTodoRequest_Todo) Reset() {
	*x = CreateTodoRequest_Todo{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest_Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest_Todo) ProtoMessage() {}

func (x *CreateTodoRequest_Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTodoRequest_Todo) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *CreateTodoRequest_Todo) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateTodoRequest_Todo) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateTodoRequest_Todo) GetState() TodoModel_State {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return TodoModel_STATE_UNSPECIFIED
}

func (x *CreateTodoRequest_Todo) GetPriority() TodoModel_Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Priority
		}
	}
	return TodoModel_PRIORITY_UNSPECIFIED
}

func (x *CreateTodoRequest_Todo) GetAssignee() int64 {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return 0
}

func (x *CreateTodoRequest_Todo) GetDueDate() *date.Date {
	if x != nil {
		return x.xxx_hidden_DueDate
	}
	return nil
}

func (x *CreateTodoRequest_Todo) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *CreateTodoRequest_Todo) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *CreateTodoRequest_Todo) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *CreateTodoRequest_Todo) SetState(v TodoModel_State) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *CreateTodoRequest_Todo) SetPriority(v TodoModel_Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *CreateTodoRequest_Todo) SetAssignee(v int64) {
	x.xxx_hidden_Assignee = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *CreateTodoRequest_Todo) SetDueDate(v *date.Date) {
	x.xxx_hidden_DueDate = v
}

func (x *CreateTodoRequest_Todo) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateTodoRequest_Todo) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateTodoRequest_Todo) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateTodoRequest_Todo) HasAssignee() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CreateTodoRequest_Todo) HasDueDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DueDate != nil
}

func (x *CreateTodoRequest_Todo) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *CreateTodoRequest_Todo) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = TodoModel_STATE_UNSPECIFIED
}

func (x *CreateTodoRequest_Todo) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Priority = TodoModel_PRIORITY_UNSPECIFIED
}

func (x *CreateTodoRequest_Todo) ClearAssignee() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Assignee = 0
}

func (x *CreateTodoRequest_Todo) ClearDueDate() {
	x.xxx_hidden_DueDate = nil
}

type CreateTodoRequest_Todo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId      int64
	Title       string
	Description *string
	State       *TodoModel_State
	Priority    *TodoModel_Priority
	Assignee    *int64
	DueDate     *date.Date
}

func (b0 CreateTodoRequest_Todo_builder) Build() *CreateTodoRequest_Todo {
	m0 := &CreateTodoRequest_Todo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Title = b.Title
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Description = b.Description
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_State = *b.State
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Priority = *b.Priority
	}
	if b.Assignee != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Assignee = *b.Assignee
	}
	x.xxx_hidden_DueDate = b.DueDate
	return m0
}

type CreateTodoRequest_SubTask struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTodoRequest_SubTask) Reset() {
	*x = CreateTodoRequest_SubTask{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest_SubTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest_SubTask) ProtoMessage() {}

func (x *CreateTodoRequest_SubTask) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTodoRequest_SubTask) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateTodoRequest_SubTask) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

type CreateTodoRequest_SubTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title string
}

func (b0 CreateTodoRequest_SubTask_builder) Build() *CreateTodoRequest_SubTask {
	m0 := &CreateTodoRequest_SubTask{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	return m0
}

type ListTodosRequest_Filter struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_States     []TodoModel_State      `protobuf:"varint,1,rep,packed,name=states,proto3,enum=todo.v1.TodoModel_State"`
	xxx_hidden_Priorities []TodoModel_Priority   `protobuf:"varint,2,rep,packed,name=priorities,proto3,enum=todo.v1.TodoModel_Priority"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListTodosRequest_Filter) Reset() {
	*x = ListTodosRequest_Filter{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest_Filter) ProtoMessage() {}

func (x *ListTodosRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest_Filter) GetStates() []TodoModel_State {
	if x != nil {
		return x.xxx_hidden_States
	}
	return nil
}

func (x *ListTodosRequest_Filter) GetPriorities() []TodoModel_Priority {
	if x != nil {
		return x.xxx_hidden_Priorities
	}
	return nil
}

func (x *ListTodosRequest_Filter) SetStates(v []TodoModel_State) {
	x.xxx_hidden_States = v
}

func (x *ListTodosRequest_Filter) SetPriorities(v []TodoModel_Priority) {
	x.xxx_hidden_Priorities = v
}

type ListTodosRequest_Filter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	States     []TodoModel_State
	Priorities []TodoModel_Priority
}

func (b0 ListTodosRequest_Filter_builder) Build() *ListTodosRequest_Filter {
	m0 := &ListTodosRequest_Filter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_States = b.States
	x.xxx_hidden_Priorities = b.Priorities
	return m0
}

type ListTodosRequest_OrderBy struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field  string                 `protobuf:"bytes,1,opt,name=field,proto3"`
	xxx_hidden_IsDesc bool                   `protobuf:"varint,2,opt,name=is_desc,json=isDesc,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTodosRequest_OrderBy) Reset() {
	*x = ListTodosRequest_OrderBy{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest_OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest_OrderBy) ProtoMessage() {}

func (x *ListTodosRequest_OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest_OrderBy) GetField() string {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return ""
}

func (x *ListTodosRequest_OrderBy) GetIsDesc() bool {
	if x != nil {
		return x.xxx_hidden_IsDesc
	}
	return false
}

func (x *ListTodosRequest_OrderBy) SetField(v string) {
	x.xxx_hidden_Field = v
}

func (x *ListTodosRequest_OrderBy) SetIsDesc(v bool) {
	x.xxx_hidden_IsDesc = v
}

type ListTodosRequest_OrderBy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field  string
	IsDesc bool
}

func (b0 ListTodosRequest_OrderBy_builder) Build() *ListTodosRequest_OrderBy {
	m0 := &ListTodosRequest_OrderBy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Field = b.Field
	x.xxx_hidden_IsDesc = b.IsDesc
	return m0
}

type UpdateTodoRequest_Todo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
	xxx_hidden_State       TodoModel_State        `protobuf:"varint,4,opt,name=state,proto3,enum=todo.v1.TodoModel_State,oneof"`
	xxx_hidden_Priority    TodoModel_Priority     `protobuf:"varint,5,opt,name=priority,proto3,enum=todo.v1.TodoModel_Priority,oneof"`
	xxx_hidden_Assignee    int64                  `protobuf:"varint,6,opt,name=assignee,proto3,oneof"`
	xxx_hidden_DueDate     *date.Date             `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateTodoRequest_Todo) Reset() {
	*x = UpdateTodoRequest_Todo{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest_Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest_Todo) ProtoMessage() {}

func (x *UpdateTodoRequest_Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest_Todo) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateTodoRequest_Todo) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateTodoRequest_Todo) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdateTodoRequest_Todo) GetState() TodoModel_State {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return TodoModel_STATE_UNSPECIFIED
}

func (x *UpdateTodoRequest_Todo) GetPriority() TodoModel_Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Priority
		}
	}
	return TodoModel_PRIORITY_UNSPECIFIED
}

func (x *UpdateTodoRequest_Todo) GetAssignee() int64 {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return 0
}

func (x *UpdateTodoRequest_Todo) GetDueDate() *date.Date {
	if x != nil {
		return x.xxx_hidden_DueDate
	}
	return nil
}

func (x *UpdateTodoRequest_Todo) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *UpdateTodoRequest_Todo) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *UpdateTodoRequest_Todo) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *UpdateTodoRequest_Todo) SetState(v TodoModel_State) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *UpdateTodoRequest_Todo) SetPriority(v TodoModel_Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *UpdateTodoRequest_Todo) SetAssignee(v int64) {
	x.xxx_hidden_Assignee = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *UpdateTodoRequest_Todo) SetDueDate(v *date.Date) {
	x.xxx_hidden_DueDate = v
}

func (x *UpdateTodoRequest_Todo) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateTodoRequest_Todo) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateTodoRequest_Todo) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateTodoRequest_Todo) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateTodoRequest_Todo) HasAssignee() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UpdateTodoRequest_Todo) HasDueDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DueDate != nil
}

func (x *UpdateTodoRequest_Todo) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *UpdateTodoRequest_Todo) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *UpdateTodoRequest_Todo) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = TodoModel_STATE_UNSPECIFIED
}

func (x *UpdateTodoRequest_Todo) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Priority = TodoModel_PRIORITY_UNSPECIFIED
}

func (x *UpdateTodoRequest_Todo) ClearAssignee() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Assignee = 0
}

func (x *UpdateTodoRequest_Todo) ClearDueDate() {
	x.xxx_hidden_DueDate = nil
}

type UpdateTodoRequest_Todo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          int64
	Title       *string
	Description *string
	State       *TodoModel_State
	Priority    *TodoModel_Priority
	Assignee    *int64
	DueDate     *date.Date
}

func (b0 UpdateTodoRequest_Todo_builder) Build() *UpdateTodoRequest_Todo {
	m0 := &UpdateTodoRequest_Todo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Description = b.Description
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_State = *b.State
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Priority = *b.Priority
	}
	if b.Assignee != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Assignee = *b.Assignee
	}
	x.xxx_hidden_DueDate = b.DueDate
	return m0
}

type UpdateTodoRequest_SubTask struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateTodoRequest_SubTask) Reset() {
	*x = UpdateTodoRequest_SubTask{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest_SubTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest_SubTask) ProtoMessage() {}

func (x *UpdateTodoRequest_SubTask) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest_SubTask) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateTodoRequest_SubTask) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateTodoRequest_SubTask) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *UpdateTodoRequest_SubTask) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateTodoRequest_SubTask) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateTodoRequest_SubTask) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

type UpdateTodoRequest_SubTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    int64
	Title *string
}

func (b0 UpdateTodoRequest_SubTask_builder) Build() *UpdateTodoRequest_SubTask {
	m0 := &UpdateTodoRequest_SubTask{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Title = b.Title
	}
	return m0
}

type UpdateTodoRequest_SubTaskOperation struct {
	state                protoimpl.MessageState                         `protogen:"opaque.v1"`
	xxx_hidden_Operation isUpdateTodoRequest_SubTaskOperation_Operation `protobuf_oneof:"operation"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTodoRequest_SubTaskOperation) Reset() {
	*x = UpdateTodoRequest_SubTaskOperation{}
	mi := &file_todo_v1_todo_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest_SubTaskOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest_SubTaskOperation) ProtoMessage() {}

func (x *UpdateTodoRequest_SubTaskOperation) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest_SubTaskOperation) GetCreate() *CreateTodoRequest_SubTask {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *UpdateTodoRequest_SubTaskOperation) GetUpdate() *UpdateTodoRequest_SubTask {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *UpdateTodoRequest_SubTaskOperation) GetDelete() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete); ok {
			return x.Delete
		}
	}
	return 0
}

func (x *UpdateTodoRequest_SubTaskOperation) SetCreate(v *CreateTodoRequest_SubTask) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Create{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) SetUpdate(v *UpdateTodoRequest_SubTask) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Update{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) SetDelete(v int64) {
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Delete{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *UpdateTodoRequest_SubTaskOperation) HasCreate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) HasUpdate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) HasDelete() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearCreate() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearUpdate() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearDelete() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete); ok {
		x.xxx_hidden_Operation = nil
	}
}

const UpdateTodoRequest_SubTaskOperation_Operation_not_set_case case_UpdateTodoRequest_SubTaskOperation_Operation = 0
const UpdateTodoRequest_SubTaskOperation_Create_case case_UpdateTodoRequest_SubTaskOperation_Operation = 1
const UpdateTodoRequest_SubTaskOperation_Update_case case_UpdateTodoRequest_SubTaskOperation_Operation = 2
const UpdateTodoRequest_SubTaskOperation_Delete_case case_UpdateTodoRequest_SubTaskOperation_Operation = 3

func (x *UpdateTodoRequest_SubTaskOperation) WhichOperation() case_UpdateTodoRequest_SubTaskOperation_Operation {
	if x == nil {
		return UpdateTodoRequest_SubTaskOperation_Operation_not_set_case
	}
	switch x.xxx_hidden_Operation.(type) {
	case *updateTodoRequest_SubTaskOperation_Create:
		return UpdateTodoRequest_SubTaskOperation_Create_case
	case *updateTodoRequest_SubTaskOperation_Update:
		return UpdateTodoRequest_SubTaskOperation_Update_case
	case *updateTodoRequest_SubTaskOperation_Delete:
		return UpdateTodoRequest_SubTaskOperation_Delete_case
	default:
		return UpdateTodoRequest_SubTaskOperation_Operation_not_set_case
	}
}

type UpdateTodoRequest_SubTaskOperation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Operation:
	Create *CreateTodoRequest_SubTask
	Update *UpdateTodoRequest_SubTask
	Delete *int64
	// -- end of xxx_hidden_Operation
}

func (b0 UpdateTodoRequest_SubTaskOperation_builder) Build() *UpdateTodoRequest_SubTaskOperation {
	m0 := &UpdateTodoRequest_SubTaskOperation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Create != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Create{b.Create}
	}
	if b.Update != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Update{b.Update}
	}
	if b.Delete != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Delete{*b.Delete}
	}
	return m0
}

type case_UpdateTodoRequest_SubTaskOperation_Operation protoreflect.FieldNumber

func (x case_UpdateTodoRequest_SubTaskOperation_Operation) String() string {
	md := file_todo_v1_todo_service_proto_msgTypes[14].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUpdateTodoRequest_SubTaskOperation_Operation interface {
	isUpdateTodoRequest_SubTaskOperation_Operation()
}

type updateTodoRequest_SubTaskOperation_Create struct {
	Create *CreateTodoRequest_SubTask `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type updateTodoRequest_SubTaskOperation_Update struct {
	Update *UpdateTodoRequest_SubTask `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type updateTodoRequest_SubTaskOperation_Delete struct {
	Delete int64 `protobuf:"varint,3,opt,name=delete,proto3,oneof"`
}

func (*updateTodoRequest_SubTaskOperation_Create) isUpdateTodoRequest_SubTaskOperation_Operation() {}

func (*updateTodoRequest_SubTaskOperation_Update) isUpdateTodoRequest_SubTaskOperation_Operation() {}

func (*updateTodoRequest_SubTaskOperation_Delete) isUpdateTodoRequest_SubTaskOperation_Operation() {}

var File_todo_v1_todo_service_proto protoreflect.FileDescriptor

const file_todo_v1_todo_service_proto_rawDesc = "" +
	"\n" +
	"\x1atodo/v1/todo_service.proto\x12\atodo.v1\x1a\x12todo/v1/todo.proto\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16google/type/date.proto\"\x91\x04\n" +
	"\x11CreateTodoRequest\x123\n" +
	"\x04todo\x18\x01 \x01(\v2\x1f.todo.v1.CreateTodoRequest.TodoR\x04todo\x12?\n" +
	"\tsub_tasks\x18\x02 \x03(\v2\".todo.v1.CreateTodoRequest.SubTaskR\bsubTasks\x1a\xe4\x02\n" +
	"\x04Todo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x123\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.todo.v1.TodoModel.StateH\x01R\x05state\x88\x01\x01\x12<\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1b.todo.v1.TodoModel.PriorityH\x02R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bassignee\x18\x06 \x01(\x03H\x03R\bassignee\x88\x01\x01\x121\n" +
	"\bdue_date\x18\a \x01(\v2\x11.google.type.DateH\x04R\adueDate\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_assigneeB\v\n" +
	"\t_due_date\x1a\x1f\n" +
	"\aSubTask\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"Y\n" +
	"\x0eGetTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\fshow_deleted\x18\x02 \x01(\bH\x00R\vshowDeleted\x88\x01\x01B\x0f\n" +
	"\r_show_deleted\"\xdb\x03\n" +
	"\x10ListTodosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12=\n" +
	"\x06filter\x18\x04 \x01(\v2 .todo.v1.ListTodosRequest.FilterH\x00R\x06filter\x88\x01\x01\x12<\n" +
	"\border_by\x18\x05 \x03(\v2!.todo.v1.ListTodosRequest.OrderByR\aorderBy\x12&\n" +
	"\fshow_deleted\x18\x06 \x01(\bH\x01R\vshowDeleted\x88\x01\x01\x1aw\n" +
	"\x06Filter\x120\n" +
	"\x06states\x18\x01 \x03(\x0e2\x18.todo.v1.TodoModel.StateR\x06states\x12;\n" +
	"\n" +
	"priorities\x18\x02 \x03(\x0e2\x1b.todo.v1.TodoModel.PriorityR\n" +
	"priorities\x1a8\n" +
	"\aOrderBy\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x17\n" +
	"\ais_desc\x18\x02 \x01(\bR\x06isDescB\t\n" +
	"\a_filterB\x0f\n" +
	"\r_show_deleted\"\x84\x01\n" +
	"\x11ListTodosResponse\x12(\n" +
	"\x05todos\x18\x01 \x03(\v2\x12.todo.v1.TodoModelR\x05todos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\x8a\x06\n" +
	"\x11UpdateTodoRequest\x123\n" +
	"\x04todo\x18\x01 \x01(\v2\x1f.todo.v1.UpdateTodoRequest.TodoR\x04todo\x12[\n" +
	"\x13sub_task_operations\x18\x02 \x03(\v2+.todo.v1.UpdateTodoRequest.SubTaskOperationR\x11subTaskOperations\x1a\xea\x02\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x123\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.todo.v1.TodoModel.StateH\x02R\x05state\x88\x01\x01\x12<\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1b.todo.v1.TodoModel.PriorityH\x03R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bassignee\x18\x06 \x01(\x03H\x04R\bassignee\x88\x01\x01\x121\n" +
	"\bdue_date\x18\a \x01(\v2\x11.google.type.DateH\x05R\adueDate\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_assigneeB\v\n" +
	"\t_due_date\x1a>\n" +
	"\aSubTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title\x1a\xb5\x01\n" +
	"\x10SubTaskOperation\x12<\n" +
	"\x06create\x18\x01 \x01(\v2\".todo.v1.CreateTodoRequest.SubTaskH\x00R\x06create\x12<\n" +
	"\x06update\x18\x02 \x01(\v2\".todo.v1.UpdateTodoRequest.SubTaskH\x00R\x06update\x12\x18\n" +
	"\x06delete\x18\x03 \x01(\x03H\x00R\x06deleteB\v\n" +
	"\toperation\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x14BatchGetTodosRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12&\n" +
	"\fshow_deleted\x18\x02 \x01(\bH\x00R\vshowDeleted\x88\x01\x01B\x0f\n" +
	"\r_show_deleted\"A\n" +
	"\x15BatchGetTodosResponse\x12(\n" +
	"\x05todos\x18\x01 \x03(\v2\x12.todo.v1.TodoModelR\x05todos2\x9f\x03\n" +
	"\vTodoService\x12>\n" +
	"\n" +
	"CreateTodo\x12\x1a.todo.v1.CreateTodoRequest\x1a\x12.todo.v1.TodoModel\"\x00\x128\n" +
	"\aGetTodo\x12\x17.todo.v1.GetTodoRequest\x1a\x12.todo.v1.TodoModel\"\x00\x12D\n" +
	"\tListTodos\x12\x19.todo.v1.ListTodosRequest\x1a\x1a.todo.v1.ListTodosResponse\"\x00\x12>\n" +
	"\n" +
	"UpdateTodo\x12\x1a.todo.v1.UpdateTodoRequest\x1a\x12.todo.v1.TodoModel\"\x00\x12>\n" +
	"\n" +
	"DeleteTodo\x12\x1a.todo.v1.DeleteTodoRequest\x1a\x12.todo.v1.TodoModel\"\x00\x12P\n" +
	"\rBatchGetTodos\x12\x1d.todo.v1.BatchGetTodosRequest\x1a\x1e.todo.v1.BatchGetTodosResponse\"\x00B\\\n" +
	"\x16monorepo.proto.todo.v1P\x01Z@github.com/yourorg/monorepo/packages/proto-gen-go/todo/v1;todov1b\x06proto3"

var file_todo_v1_todo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_todo_v1_todo_service_proto_goTypes = []any{
	(*CreateTodoRequest)(nil),                  // 0: todo.v1.CreateTodoRequest
	(*GetTodoRequest)(nil),                     // 1: todo.v1.GetTodoRequest
	(*ListTodosRequest)(nil),                   // 2: todo.v1.ListTodosRequest
	(*ListTodosResponse)(nil),                  // 3: todo.v1.ListTodosResponse
	(*UpdateTodoRequest)(nil),                  // 4: todo.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil),                  // 5: todo.v1.DeleteTodoRequest
	(*BatchGetTodosRequest)(nil),               // 6: todo.v1.BatchGetTodosRequest
	(*BatchGetTodosResponse)(nil),              // 7: todo.v1.BatchGetTodosResponse
	(*CreateTodoRequest_Todo)(nil),             // 8: todo.v1.CreateTodoRequest.Todo
	(*CreateTodoRequest_SubTask)(nil),          // 9: todo.v1.CreateTodoRequest.SubTask
	(*ListTodosRequest_Filter)(nil),            // 10: todo.v1.ListTodosRequest.Filter
	(*ListTodosRequest_OrderBy)(nil),           // 11: todo.v1.ListTodosRequest.OrderBy
	(*UpdateTodoRequest_Todo)(nil),             // 12: todo.v1.UpdateTodoRequest.Todo
	(*UpdateTodoRequest_SubTask)(nil),          // 13: todo.v1.UpdateTodoRequest.SubTask
	(*UpdateTodoRequest_SubTaskOperation)(nil), // 14: todo.v1.UpdateTodoRequest.SubTaskOperation
	(*TodoModel)(nil),                          // 15: todo.v1.TodoModel
	(TodoModel_State)(0),                       // 16: todo.v1.TodoModel.State
	(TodoModel_Priority)(0),                    // 17: todo.v1.TodoModel.Priority
	(*date.Date)(nil),                          // 18: google.type.Date
}
var file_todo_v1_todo_service_proto_depIdxs = []int32{
	8,  // 0: todo.v1.CreateTodoRequest.todo:type_name -> todo.v1.CreateTodoRequest.Todo
	9,  // 1: todo.v1.CreateTodoRequest.sub_tasks:type_name -> todo.v1.CreateTodoRequest.SubTask
	10, // 2: todo.v1.ListTodosRequest.filter:type_name -> todo.v1.ListTodosRequest.Filter
	11, // 3: todo.v1.ListTodosRequest.order_by:type_name -> todo.v1.ListTodosRequest.OrderBy
	15, // 4: todo.v1.ListTodosResponse.todos:type_name -> todo.v1.TodoModel
	12, // 5: todo.v1.UpdateTodoRequest.todo:type_name -> todo.v1.UpdateTodoRequest.Todo
	14, // 6: todo.v1.UpdateTodoRequest.sub_task_operations:type_name -> todo.v1.UpdateTodoRequest.SubTaskOperation
	15, // 7: todo.v1.BatchGetTodosResponse.todos:type_name -> todo.v1.TodoModel
	16, // 8: todo.v1.CreateTodoRequest.Todo.state:type_name -> todo.v1.TodoModel.State
	17, // 9: todo.v1.CreateTodoRequest.Todo.priority:type_name -> todo.v1.TodoModel.Priority
	18, // 10: todo.v1.CreateTodoRequest.Todo.due_date:type_name -> google.type.Date
	16, // 11: todo.v1.ListTodosRequest.Filter.states:type_name -> todo.v1.TodoModel.State
	17, // 12: todo.v1.ListTodosRequest.Filter.priorities:type_name -> todo.v1.TodoModel.Priority
	16, // 13: todo.v1.UpdateTodoRequest.Todo.state:type_name -> todo.v1.TodoModel.State
	17, // 14: todo.v1.UpdateTodoRequest.Todo.priority:type_name -> todo.v1.TodoModel.Priority
	18, // 15: todo.v1.UpdateTodoRequest.Todo.due_date:type_name -> google.type.Date
	9,  // 16: todo.v1.UpdateTodoRequest.SubTaskOperation.create:type_name -> todo.v1.CreateTodoRequest.SubTask
	13, // 17: todo.v1.UpdateTodoRequest.SubTaskOperation.update:type_name -> todo.v1.UpdateTodoRequest.SubTask
	0,  // 18: todo.v1.TodoService.CreateTodo:input_type -> todo.v1.CreateTodoRequest
	1,  // 19: todo.v1.TodoService.GetTodo:input_type -> todo.v1.GetTodoRequest
	2,  // 20: todo.v1.TodoService.ListTodos:input_type -> todo.v1.ListTodosRequest
	4,  // 21: todo.v1.TodoService.UpdateTodo:input_type -> todo.v1.UpdateTodoRequest
	5,  // 22: todo.v1.TodoService.DeleteTodo:input_type -> todo.v1.DeleteTodoRequest
	6,  // 23: todo.v1.TodoService.BatchGetTodos:input_type -> todo.v1.BatchGetTodosRequest
	15, // 24: todo.v1.TodoService.CreateTodo:output_type -> todo.v1.TodoModel
	15, // 25: todo.v1.TodoService.GetTodo:output_type -> todo.v1.TodoModel
	3,  // 26: todo.v1.TodoService.ListTodos:output_type -> todo.v1.ListTodosResponse
	15, // 27: todo.v1.TodoService.UpdateTodo:output_type -> todo.v1.TodoModel
	15, // 28: todo.v1.TodoService.DeleteTodo:output_type -> todo.v1.TodoModel
	7,  // 29: todo.v1.TodoService.BatchGetTodos:output_type -> todo.v1.BatchGetTodosResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_todo_v1_todo_service_proto_init() }
func file_todo_v1_todo_service_proto_init() {
	if File_todo_v1_todo_service_proto != nil {
		return
	}
	file_todo_v1_todo_proto_init()
	file_todo_v1_todo_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_todo_v1_todo_service_proto_msgTypes[14].OneofWrappers = []any{
		(*updateTodoRequest_SubTaskOperation_Create)(nil),
		(*updateTodoRequest_SubTaskOperation_Update)(nil),
		(*updateTodoRequest_SubTaskOperation_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_v1_todo_service_proto_rawDesc), len(file_todo_v1_todo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_v1_todo_service_proto_goTypes,
		DependencyIndexes: file_todo_v1_todo_service_proto_depIdxs,
		MessageInfos:      file_todo_v1_todo_service_proto_msgTypes,
	}.Build()
	File_todo_v1_todo_service_proto = out.File
	file_todo_v1_todo_service_proto_goTypes = nil
	file_todo_v1_todo_service_proto_depIdxs = nil
}
