// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monorepo/order/v1/everything_edition2023.proto
// Protobuf Java Version: 4.33.2

package monorepo.proto.order.v1;

@com.google.protobuf.Generated
public final class EverythingEdition2023Proto extends com.google.protobuf.GeneratedFile {
  private EverythingEdition2023Proto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "EverythingEdition2023Proto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt32StringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapInt32StringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt64StringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapInt64StringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapBoolStringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapBoolStringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringStringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapStringStringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringBytesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapStringBytesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringMessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapStringMessageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringEnumEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MapStringEnumEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_DeprecatedMapStringInt32Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_DeprecatedMapStringInt32Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringStringMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MaStringStringMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringEnumMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_MaStringEnumMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_EverythingEdition2023_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_EverythingEdition2023_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.monorepo/order/v1/everything_edition20" +
      "23.proto\022\021monorepo.order.v1\032\036google/prot" +
      "obuf/duration.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\036google/protobuf/wrappers.p" +
      "roto\032\026google/type/date.proto\032\033google/typ" +
      "e/dayofweek.proto\032\027google/type/month.pro" +
      "to\032\033google/type/timeofday.proto\"\307#\n\025Ever" +
      "ythingEdition2023\022\024\n\005int32\030\001 \001(\005R\005int32\022" +
      "\024\n\005int64\030\003 \001(\003R\005int64\022\024\n\005float\030\013 \001(\002R\005fl" +
      "oat\022\026\n\006double\030\014 \001(\001R\006double\022\022\n\004bool\030\r \001(" +
      "\010R\004bool\022\026\n\006string\030\016 \001(\tR\006string\022\024\n\005bytes" +
      "\030\017 \001(\014R\005bytes\022%\n\016repeated_int32\030\020 \003(\005R\rr" +
      "epeatedInt32\022%\n\016repeated_int64\030\022 \003(\003R\rre" +
      "peatedInt64\022%\n\016repeated_float\030\032 \003(\002R\rrep" +
      "eatedFloat\022\'\n\017repeated_double\030\033 \003(\001R\016rep" +
      "eatedDouble\022#\n\rrepeated_bool\030\034 \003(\010R\014repe" +
      "atedBool\022\'\n\017repeated_string\030\035 \003(\tR\016repea" +
      "tedString\022%\n\016repeated_bytes\030\036 \003(\014R\rrepea" +
      "tedBytes\022<\n\013int32_value\030\024 \001(\0132\033.google.p" +
      "rotobuf.Int32ValueR\nint32Value\022<\n\013int64_" +
      "value\030\025 \001(\0132\033.google.protobuf.Int64Value" +
      "R\nint64Value\022<\n\013float_value\030\026 \001(\0132\033.goog" +
      "le.protobuf.FloatValueR\nfloatValue\022?\n\014do" +
      "uble_value\030\027 \001(\0132\034.google.protobuf.Doubl" +
      "eValueR\013doubleValue\0229\n\nbool_value\030\030 \001(\0132" +
      "\032.google.protobuf.BoolValueR\tboolValue\022?" +
      "\n\014string_value\030\031 \001(\0132\034.google.protobuf.S" +
      "tringValueR\013stringValue\022<\n\013bytes_value\030\037" +
      " \001(\0132\033.google.protobuf.BytesValueR\nbytes" +
      "Value\022f\n\020map_int32_string\030  \003(\0132<.monore" +
      "po.order.v1.EverythingEdition2023.MapInt" +
      "32StringEntryR\016mapInt32String\022f\n\020map_int" +
      "64_string\030\" \003(\0132<.monorepo.order.v1.Ever" +
      "ythingEdition2023.MapInt64StringEntryR\016m" +
      "apInt64String\022c\n\017map_bool_string\030, \003(\0132;" +
      ".monorepo.order.v1.EverythingEdition2023" +
      ".MapBoolStringEntryR\rmapBoolString\022i\n\021ma" +
      "p_string_string\030- \003(\0132=.monorepo.order.v" +
      "1.EverythingEdition2023.MapStringStringE" +
      "ntryR\017mapStringString\022f\n\020map_string_byte" +
      "s\030. \003(\0132<.monorepo.order.v1.EverythingEd" +
      "ition2023.MapStringBytesEntryR\016mapString" +
      "Bytes\022J\n\007message\0302 \001(\01320.monorepo.order." +
      "v1.EverythingEdition2023.MessageR\007messag" +
      "e\022[\n\020repeated_message\0303 \003(\01320.monorepo.o" +
      "rder.v1.EverythingEdition2023.MessageR\017r" +
      "epeatedMessage\022l\n\022map_string_message\0304 \003" +
      "(\0132>.monorepo.order.v1.EverythingEdition" +
      "2023.MapStringMessageEntryR\020mapStringMes" +
      "sage\022A\n\004enum\030< \001(\0162-.monorepo.order.v1.E" +
      "verythingEdition2023.EnumR\004enum\022Y\n\roptio" +
      "nal_enum\030> \001(\0162-.monorepo.order.v1.Every" +
      "thingEdition2023.EnumB\005\252\001\002\010\002R\014optionalEn" +
      "um\022R\n\rrepeated_enum\030= \003(\0162-.monorepo.ord" +
      "er.v1.EverythingEdition2023.EnumR\014repeat" +
      "edEnum\022c\n\017map_string_enum\030? \003(\0132;.monore" +
      "po.order.v1.EverythingEdition2023.MapStr" +
      "ingEnumEntryR\rmapStringEnum\0228\n\ttimestamp" +
      "\030A \001(\0132\032.google.protobuf.TimestampR\ttime" +
      "stamp\0225\n\010duration\030B \001(\0132\031.google.protobu" +
      "f.DurationR\010duration\0226\n\013time_of_day\030F \001(" +
      "\0132\026.google.type.TimeOfDayR\ttimeOfDay\022%\n\004" +
      "date\030G \001(\0132\021.google.type.DateR\004date\0226\n\013d" +
      "ay_of_week\030I \001(\0162\026.google.type.DayOfWeek" +
      "R\tdayOfWeek\022(\n\005month\030J \001(\0162\022.google.type" +
      ".MonthR\005month\022!\n\013oneof_int32\030P \001(\005H\000R\non" +
      "eofInt32\022#\n\014oneof_string\030Q \001(\tH\000R\013oneofS" +
      "tring\022N\n\noneof_enum\030R \001(\0162-.monorepo.ord" +
      "er.v1.EverythingEdition2023.EnumH\000R\toneo" +
      "fEnum\022W\n\roneof_message\030S \001(\01320.monorepo." +
      "order.v1.EverythingEdition2023.MessageH\000" +
      "R\014oneofMessage\022-\n\020deprecated_int32\030Z \001(\005" +
      "B\002\030\001R\017deprecatedInt32\022/\n\021deprecated_stri" +
      "ng\030[ \001(\tB\002\030\001R\020deprecatedString\022@\n\032deprec" +
      "ated_repeated_string\030\\ \003(\tB\002\030\001R\030deprecat" +
      "edRepeatedString\022\211\001\n\033deprecated_map_stri" +
      "ng_int32\030] \003(\0132F.monorepo.order.v1.Every" +
      "thingEdition2023.DeprecatedMapStringInt3" +
      "2EntryB\002\030\001R\030deprecatedMapStringInt32\022Z\n\017" +
      "deprecated_enum\030^ \001(\0162-.monorepo.order.v" +
      "1.EverythingEdition2023.EnumB\002\030\001R\016deprec" +
      "atedEnum\022\033\n\tstr_bytes\030d \001(\tR\010strBytes\022H\n" +
      "\010en_value\030e \001(\0162-.monorepo.order.v1.Ever" +
      "ythingEdition2023.EnumR\007enValue\022$\n\016re_st" +
      "ring_list\030f \003(\tR\014reStringList\022Z\n\022re_enum" +
      "_value_list\030k \003(\0162-.monorepo.order.v1.Ev" +
      "erythingEdition2023.EnumR\017reEnumValueLis" +
      "t\022p\n\024ma_string_string_map\030g \003(\0132?.monore" +
      "po.order.v1.EverythingEdition2023.MaStri" +
      "ngStringMapEntryR\021maStringStringMap\022j\n\022m" +
      "a_string_enum_map\030h \003(\0132=.monorepo.order" +
      ".v1.EverythingEdition2023.MaStringEnumMa" +
      "pEntryR\017maStringEnumMap\022Q\n\013msg_builder\030i" +
      " \001(\01320.monorepo.order.v1.EverythingEditi" +
      "on2023.MessageR\nmsgBuilder\022V\n\016msg_or_bui" +
      "lder\030j \001(\01320.monorepo.order.v1.Everythin" +
      "gEdition2023.MessageR\014msgOrBuilder\032A\n\023Ma" +
      "pInt32StringEntry\022\020\n\003key\030\001 \001(\005R\003key\022\024\n\005v" +
      "alue\030\002 \001(\tR\005value:\0028\001\032A\n\023MapInt64StringE" +
      "ntry\022\020\n\003key\030\001 \001(\003R\003key\022\024\n\005value\030\002 \001(\tR\005v" +
      "alue:\0028\001\032@\n\022MapBoolStringEntry\022\020\n\003key\030\001 " +
      "\001(\010R\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032B\n\024Ma" +
      "pStringStringEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005" +
      "value\030\002 \001(\tR\005value:\0028\001\032A\n\023MapStringBytes" +
      "Entry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\014R\005" +
      "value:\0028\001\032u\n\025MapStringMessageEntry\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022F\n\005value\030\002 \001(\01320.monorepo.o" +
      "rder.v1.EverythingEdition2023.MessageR\005v" +
      "alue:\0028\001\032o\n\022MapStringEnumEntry\022\020\n\003key\030\001 " +
      "\001(\tR\003key\022C\n\005value\030\002 \001(\0162-.monorepo.order" +
      ".v1.EverythingEdition2023.EnumR\005value:\0028" +
      "\001\032K\n\035DeprecatedMapStringInt32Entry\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\005R\005value:\0028\001\032D" +
      "\n\026MaStringStringMapEntry\022\020\n\003key\030\001 \001(\tR\003k" +
      "ey\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032q\n\024MaString" +
      "EnumMapEntry\022\020\n\003key\030\001 \001(\tR\003key\022C\n\005value\030" +
      "\002 \001(\0162-.monorepo.order.v1.EverythingEdit" +
      "ion2023.EnumR\005value:\0028\001\032-\n\007Message\022\016\n\002id" +
      "\030\001 \001(\003R\002id\022\022\n\004name\030\002 \001(\tR\004name\"@\n\004Enum\022\024" +
      "\n\020ENUM_UNSPECIFIED\020\000\022\020\n\014ENUM_VALUE_1\020\001\022\020" +
      "\n\014ENUM_VALUE_2\020\002B\007\n\005oneofB\227\001\n\027monorepo.p" +
      "roto.order.v1B\032EverythingEdition2023Prot" +
      "oP\001Z^github.com/yourorg/monorepo/package" +
      "s/proto-gen-go/monorepo/order/pkg/monore" +
      "po/order/v1;orderv1b\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
          com.google.type.DayOfWeekProto.getDescriptor(),
          com.google.type.MonthProto.getDescriptor(),
          com.google.type.TimeOfDayProto.getDescriptor(),
        });
    internal_static_monorepo_order_v1_EverythingEdition2023_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_monorepo_order_v1_EverythingEdition2023_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_descriptor,
        new java.lang.String[] { "Int32", "Int64", "Float", "Double", "Bool", "String", "Bytes", "RepeatedInt32", "RepeatedInt64", "RepeatedFloat", "RepeatedDouble", "RepeatedBool", "RepeatedString", "RepeatedBytes", "Int32Value", "Int64Value", "FloatValue", "DoubleValue", "BoolValue", "StringValue", "BytesValue", "MapInt32String", "MapInt64String", "MapBoolString", "MapStringString", "MapStringBytes", "Message", "RepeatedMessage", "MapStringMessage", "Enum", "OptionalEnum", "RepeatedEnum", "MapStringEnum", "Timestamp", "Duration", "TimeOfDay", "Date", "DayOfWeek", "Month", "OneofInt32", "OneofString", "OneofEnum", "OneofMessage", "DeprecatedInt32", "DeprecatedString", "DeprecatedRepeatedString", "DeprecatedMapStringInt32", "DeprecatedEnum", "StrBytes", "EnValue", "ReStringList", "ReEnumValueList", "MaStringStringMap", "MaStringEnumMap", "MsgBuilder", "MsgOrBuilder", "Oneof", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt32StringEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(0);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt32StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapInt32StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt64StringEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(1);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapInt64StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapInt64StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapBoolStringEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(2);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapBoolStringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapBoolStringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringStringEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(3);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringStringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapStringStringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringBytesEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(4);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringBytesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapStringBytesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringMessageEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(5);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringMessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapStringMessageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringEnumEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(6);
    internal_static_monorepo_order_v1_EverythingEdition2023_MapStringEnumEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MapStringEnumEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_DeprecatedMapStringInt32Entry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(7);
    internal_static_monorepo_order_v1_EverythingEdition2023_DeprecatedMapStringInt32Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_DeprecatedMapStringInt32Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringStringMapEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(8);
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringStringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MaStringStringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringEnumMapEntry_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(9);
    internal_static_monorepo_order_v1_EverythingEdition2023_MaStringEnumMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_MaStringEnumMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_order_v1_EverythingEdition2023_Message_descriptor =
      internal_static_monorepo_order_v1_EverythingEdition2023_descriptor.getNestedType(10);
    internal_static_monorepo_order_v1_EverythingEdition2023_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_EverythingEdition2023_Message_descriptor,
        new java.lang.String[] { "Id", "Name", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
    com.google.type.DayOfWeekProto.getDescriptor();
    com.google.type.MonthProto.getDescriptor();
    com.google.type.TimeOfDayProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
