// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monorepo/order/v1/order.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.order.v1;

@com.google.protobuf.Generated
public final class Order extends com.google.protobuf.GeneratedFile {
  private Order() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Order");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_OrderModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_OrderModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_order_v1_OrderModel_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_order_v1_OrderModel_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035monorepo/order/v1/order.proto\022\021monorep" +
      "o.order.v1\032\037google/protobuf/timestamp.pr" +
      "oto\"\237\002\n\nOrderModel\022\016\n\002id\030\001 \001(\003R\002id\022\031\n\010it" +
      "em_ids\030\002 \003(\003R\007itemIds\022\035\n\nitem_names\030\003 \003(" +
      "\tR\titemNames\022M\n\nattributes\030\004 \003(\0132-.monor" +
      "epo.order.v1.OrderModel.AttributesEntryR" +
      "\nattributes\0229\n\ncreated_at\030\005 \001(\0132\032.google" +
      ".protobuf.TimestampR\tcreatedAt\032=\n\017Attrib" +
      "utesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001" +
      "(\tR\005value:\0028\001Bw\n\027monorepo.proto.order.v1" +
      "P\001ZZgithub.com/yourorg/monorepo/packages" +
      "/proto-gen-go/monorepo/order/monorepo/or" +
      "der/v1;orderv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_monorepo_order_v1_OrderModel_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_monorepo_order_v1_OrderModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_OrderModel_descriptor,
        new java.lang.String[] { "Id", "ItemIds", "ItemNames", "Attributes", "CreatedAt", });
    internal_static_monorepo_order_v1_OrderModel_AttributesEntry_descriptor =
      internal_static_monorepo_order_v1_OrderModel_descriptor.getNestedType(0);
    internal_static_monorepo_order_v1_OrderModel_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_order_v1_OrderModel_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
