package monorepo.services.todo.entity;

import jakarta.annotation.Generated;
import java.time.Instant;
import org.jspecify.annotations.Nullable;

/**
 * Database Table Remarks:
 *   Table to store subtasks associated with todos
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table todo_subtask
 */
public class TodoSubtask {
    /**
     * Database Column Remarks:
     *   Primary key of the subtask
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   Foreign key referencing the associated todo item
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.todo_id")
    private Long todoId;

    /**
     * Database Column Remarks:
     *   Title of the subtask
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.title")
    private String title;

    /**
     * Database Column Remarks:
     *   Timestamp when the subtask was created
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.created_at")
    private Instant createdAt;

    /**
     * Database Column Remarks:
     *   Timestamp when the subtask was last updated
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.updated_at")
    private Instant updatedAt;

    /**
     * Database Column Remarks:
     *   Timestamp when the subtask was deleted (soft delete)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.deleted_at")
    @Nullable
    private Instant deletedAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.todo_id")
    public Long getTodoId() {
        return todoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.todo_id")
    public void setTodoId(Long todoId) {
        this.todoId = todoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.title")
    public String getTitle() {
        return title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.title")
    public void setTitle(String title) {
        this.title = title;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.created_at")
    public Instant getCreatedAt() {
        return createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.created_at")
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.updated_at")
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.updated_at")
    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.deleted_at")
    @Nullable
    public Instant getDeletedAt() {
        return deletedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: todo_subtask.deleted_at")
    public void setDeletedAt(@Nullable Instant deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: todo_subtask")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", todoId=").append(todoId);
        sb.append(", title=").append(title);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append("]");
        return sb.toString();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: todo_subtask")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TodoSubtask other = (TodoSubtask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTodoId() == null ? other.getTodoId() == null : this.getTodoId().equals(other.getTodoId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()))
            && (this.getDeletedAt() == null ? other.getDeletedAt() == null : this.getDeletedAt().equals(other.getDeletedAt()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: todo_subtask")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTodoId() == null) ? 0 : getTodoId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        result = prime * result + ((getDeletedAt() == null) ? 0 : getDeletedAt().hashCode());
        return result;
    }
}