// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user/v1/user_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.user.v1;

@com.google.protobuf.Generated
public interface DeleteUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.DeleteUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();
}
