// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monorepo/todo/v1/todo_service.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public interface BatchGetTodosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monorepo.todo.v1.BatchGetTodosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .monorepo.todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<monorepo.proto.todo.v1.Todo> 
      getTodosList();
  /**
   * <code>repeated .monorepo.todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  monorepo.proto.todo.v1.Todo getTodos(int index);
  /**
   * <code>repeated .monorepo.todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  int getTodosCount();
  /**
   * <code>repeated .monorepo.todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<? extends monorepo.proto.todo.v1.TodoOrBuilder> 
      getTodosOrBuilderList();
  /**
   * <code>repeated .monorepo.todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  monorepo.proto.todo.v1.TodoOrBuilder getTodosOrBuilder(
      int index);
}
