// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monorepo/todo/v1/todo_service.proto
// Protobuf Java Version: 4.34.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public final class TodoServiceOuterClass extends com.google.protobuf.GeneratedFile {
  private TodoServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TodoServiceOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_CreateTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_CreateTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_GetTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_GetTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_ListTodosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_ListTodosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_ListTodosRequest_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_ListTodosRequest_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_ListTodosRequest_OrderBy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_ListTodosRequest_OrderBy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_ListTodosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_ListTodosResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_UpdateTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_UpdateTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_UpdateTodoRequest_SubTaskOperation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_UpdateTodoRequest_SubTaskOperation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_DeleteTodoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_DeleteTodoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_CreateSubtaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_CreateSubtaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_UpdateSubtaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_UpdateSubtaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_DeleteSubtaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_DeleteSubtaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_BatchGetTodosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_BatchGetTodosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_BatchGetTodosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_BatchGetTodosResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#monorepo/todo/v1/todo_service.proto\022\020m" +
      "onorepo.todo.v1\032\033google/protobuf/empty.p" +
      "roto\032 google/protobuf/field_mask.proto\032\026" +
      "google/type/date.proto\032\033monorepo/todo/v1" +
      "/todo.proto\"\224\004\n\021CreateTodoRequest\022\027\n\007use" +
      "r_id\030\001 \001(\003R\006userId\022\024\n\005title\030\002 \001(\tR\005title" +
      "\022%\n\013description\030\003 \001(\tH\000R\013description\210\001\001\022" +
      "7\n\005state\030\004 \001(\0162\034.monorepo.todo.v1.Todo.S" +
      "tateH\001R\005state\210\001\001\022@\n\010priority\030\005 \001(\0162\037.mon" +
      "orepo.todo.v1.Todo.PriorityH\002R\010priority\210" +
      "\001\001\022\037\n\010assignee\030\006 \001(\003H\003R\010assignee\210\001\001\0221\n\010d" +
      "ue_date\030\007 \001(\0132\021.google.type.DateH\004R\007dueD" +
      "ate\210\001\001\022@\n\nattributes\030\010 \003(\0132 .monorepo.to" +
      "do.v1.Todo.AttributeR\nattributes\022\022\n\004tags" +
      "\030\t \003(\tR\004tags\022C\n\tsub_tasks\030\n \003(\0132&.monore" +
      "po.todo.v1.CreateSubtaskRequestR\010subTask" +
      "sB\016\n\014_descriptionB\010\n\006_stateB\013\n\t_priority" +
      "B\013\n\t_assigneeB\013\n\t_due_date\"\203\001\n\016GetTodoRe" +
      "quest\022\016\n\002id\030\001 \001(\003R\002id\022\034\n\007user_id\030\002 \001(\003H\000" +
      "R\006userId\210\001\001\022&\n\014show_deleted\030\003 \001(\010H\001R\013sho" +
      "wDeleted\210\001\001B\n\n\010_user_idB\017\n\r_show_deleted" +
      "\"\364\004\n\020ListTodosRequest\022\033\n\tpage_size\030\001 \001(\005" +
      "R\010pageSize\022\035\n\npage_token\030\002 \001(\tR\tpageToke" +
      "n\022\027\n\007user_id\030\003 \001(\003R\006userId\022F\n\006filter\030\004 \001" +
      "(\0132).monorepo.todo.v1.ListTodosRequest.F" +
      "ilterH\000R\006filter\210\001\001\022E\n\010order_by\030\005 \003(\0132*.m" +
      "onorepo.todo.v1.ListTodosRequest.OrderBy" +
      "R\007orderBy\022&\n\014show_deleted\030\006 \001(\010H\001R\013showD" +
      "eleted\210\001\001\032\177\n\006Filter\0224\n\006states\030\001 \003(\0162\034.mo" +
      "norepo.todo.v1.Todo.StateR\006states\022?\n\npri" +
      "orities\030\002 \003(\0162\037.monorepo.todo.v1.Todo.Pr" +
      "iorityR\npriorities\032\266\001\n\007OrderBy\022F\n\005field\030" +
      "\001 \001(\01620.monorepo.todo.v1.ListTodosReques" +
      "t.OrderBy.FieldR\005field\022\027\n\007is_desc\030\002 \001(\010R" +
      "\006isDesc\"J\n\005Field\022\025\n\021FIELD_UNSPECIFIED\020\000\022" +
      "\016\n\nCREATED_AT\020\001\022\014\n\010DUE_DATE\020\002\022\014\n\010PRIORIT" +
      "Y\020\003B\t\n\007_filterB\017\n\r_show_deleted\"\210\001\n\021List" +
      "TodosResponse\022,\n\005todos\030\001 \003(\0132\026.monorepo." +
      "todo.v1.TodoR\005todos\022&\n\017next_page_token\030\002" +
      " \001(\tR\rnextPageToken\022\035\n\ntotal_size\030\003 \001(\005R" +
      "\ttotalSize\"\315\006\n\021UpdateTodoRequest\022\016\n\002id\030\001" +
      " \001(\003R\002id\022\034\n\007user_id\030\002 \001(\003H\000R\006userId\210\001\001\022\031" +
      "\n\005title\030\003 \001(\tH\001R\005title\210\001\001\022%\n\013description" +
      "\030\004 \001(\tH\002R\013description\210\001\001\0227\n\005state\030\005 \001(\0162" +
      "\034.monorepo.todo.v1.Todo.StateH\003R\005state\210\001" +
      "\001\022@\n\010priority\030\006 \001(\0162\037.monorepo.todo.v1.T" +
      "odo.PriorityH\004R\010priority\210\001\001\022\037\n\010assignee\030" +
      "\007 \001(\003H\005R\010assignee\210\001\001\0221\n\010due_date\030\010 \001(\0132\021" +
      ".google.type.DateH\006R\007dueDate\210\001\001\022@\n\nattri" +
      "butes\030\t \003(\0132 .monorepo.todo.v1.Todo.Attr" +
      "ibuteR\nattributes\022\022\n\004tags\030\n \003(\tR\004tags\022d\n" +
      "\023sub_task_operations\030\013 \003(\01324.monorepo.to" +
      "do.v1.UpdateTodoRequest.SubTaskOperation" +
      "R\021subTaskOperations\032\345\001\n\020SubTaskOperation" +
      "\022@\n\006create\030\001 \001(\0132&.monorepo.todo.v1.Crea" +
      "teSubtaskRequestH\000R\006create\022@\n\006update\030\002 \001" +
      "(\0132&.monorepo.todo.v1.UpdateSubtaskReque" +
      "stH\000R\006update\022@\n\006delete\030\003 \001(\0132&.monorepo." +
      "todo.v1.DeleteSubtaskRequestH\000R\006deleteB\013" +
      "\n\toperationB\n\n\010_user_idB\010\n\006_titleB\016\n\014_de" +
      "scriptionB\010\n\006_stateB\013\n\t_priorityB\013\n\t_ass" +
      "igneeB\013\n\t_due_date\"M\n\021DeleteTodoRequest\022" +
      "\016\n\002id\030\001 \001(\003R\002id\022\034\n\007user_id\030\002 \001(\003H\000R\006user" +
      "Id\210\001\001B\n\n\010_user_id\",\n\024CreateSubtaskReques" +
      "t\022\024\n\005title\030\001 \001(\tR\005title\"K\n\024UpdateSubtask" +
      "Request\022\016\n\002id\030\001 \001(\003R\002id\022\031\n\005title\030\002 \001(\tH\000" +
      "R\005title\210\001\001B\010\n\006_title\"&\n\024DeleteSubtaskReq" +
      "uest\022\016\n\002id\030\001 \001(\003R\002id\"a\n\024BatchGetTodosReq" +
      "uest\022\020\n\003ids\030\001 \003(\003R\003ids\022&\n\014show_deleted\030\002" +
      " \001(\010H\000R\013showDeleted\210\001\001B\017\n\r_show_deleted\"" +
      "E\n\025BatchGetTodosResponse\022,\n\005todos\030\001 \003(\0132" +
      "\026.monorepo.todo.v1.TodoR\005todos2\367\003\n\013TodoS" +
      "ervice\022K\n\nCreateTodo\022#.monorepo.todo.v1." +
      "CreateTodoRequest\032\026.monorepo.todo.v1.Tod" +
      "o\"\000\022E\n\007GetTodo\022 .monorepo.todo.v1.GetTod" +
      "oRequest\032\026.monorepo.todo.v1.Todo\"\000\022V\n\tLi" +
      "stTodos\022\".monorepo.todo.v1.ListTodosRequ" +
      "est\032#.monorepo.todo.v1.ListTodosResponse" +
      "\"\000\022K\n\nUpdateTodo\022#.monorepo.todo.v1.Upda" +
      "teTodoRequest\032\026.monorepo.todo.v1.Todo\"\000\022" +
      "K\n\nDeleteTodo\022#.monorepo.todo.v1.DeleteT" +
      "odoRequest\032\026.monorepo.todo.v1.Todo\"\000\022b\n\r" +
      "BatchGetTodos\022&.monorepo.todo.v1.BatchGe" +
      "tTodosRequest\032\'.monorepo.todo.v1.BatchGe" +
      "tTodosResponse\"\000Bw\n\026monorepo.proto.todo." +
      "v1P\001Z[github.com/yourorg/monorepo/packag" +
      "es/proto-gen-go/monorepo/todo/pkg/monore" +
      "po/todo/v1;todov1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
          monorepo.proto.todo.v1.TodoProto.getDescriptor(),
        });
    internal_static_monorepo_todo_v1_CreateTodoRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_monorepo_todo_v1_CreateTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_CreateTodoRequest_descriptor,
        new java.lang.String[] { "UserId", "Title", "Description", "State", "Priority", "Assignee", "DueDate", "Attributes", "Tags", "SubTasks", });
    internal_static_monorepo_todo_v1_GetTodoRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_monorepo_todo_v1_GetTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_GetTodoRequest_descriptor,
        new java.lang.String[] { "Id", "UserId", "ShowDeleted", });
    internal_static_monorepo_todo_v1_ListTodosRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_monorepo_todo_v1_ListTodosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_ListTodosRequest_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", "UserId", "Filter", "OrderBy", "ShowDeleted", });
    internal_static_monorepo_todo_v1_ListTodosRequest_Filter_descriptor =
      internal_static_monorepo_todo_v1_ListTodosRequest_descriptor.getNestedType(0);
    internal_static_monorepo_todo_v1_ListTodosRequest_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_ListTodosRequest_Filter_descriptor,
        new java.lang.String[] { "States", "Priorities", });
    internal_static_monorepo_todo_v1_ListTodosRequest_OrderBy_descriptor =
      internal_static_monorepo_todo_v1_ListTodosRequest_descriptor.getNestedType(1);
    internal_static_monorepo_todo_v1_ListTodosRequest_OrderBy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_ListTodosRequest_OrderBy_descriptor,
        new java.lang.String[] { "Field", "IsDesc", });
    internal_static_monorepo_todo_v1_ListTodosResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_monorepo_todo_v1_ListTodosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_ListTodosResponse_descriptor,
        new java.lang.String[] { "Todos", "NextPageToken", "TotalSize", });
    internal_static_monorepo_todo_v1_UpdateTodoRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_monorepo_todo_v1_UpdateTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_UpdateTodoRequest_descriptor,
        new java.lang.String[] { "Id", "UserId", "Title", "Description", "State", "Priority", "Assignee", "DueDate", "Attributes", "Tags", "SubTaskOperations", });
    internal_static_monorepo_todo_v1_UpdateTodoRequest_SubTaskOperation_descriptor =
      internal_static_monorepo_todo_v1_UpdateTodoRequest_descriptor.getNestedType(0);
    internal_static_monorepo_todo_v1_UpdateTodoRequest_SubTaskOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_UpdateTodoRequest_SubTaskOperation_descriptor,
        new java.lang.String[] { "Create", "Update", "Delete", "Operation", });
    internal_static_monorepo_todo_v1_DeleteTodoRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_monorepo_todo_v1_DeleteTodoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_DeleteTodoRequest_descriptor,
        new java.lang.String[] { "Id", "UserId", });
    internal_static_monorepo_todo_v1_CreateSubtaskRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_monorepo_todo_v1_CreateSubtaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_CreateSubtaskRequest_descriptor,
        new java.lang.String[] { "Title", });
    internal_static_monorepo_todo_v1_UpdateSubtaskRequest_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_monorepo_todo_v1_UpdateSubtaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_UpdateSubtaskRequest_descriptor,
        new java.lang.String[] { "Id", "Title", });
    internal_static_monorepo_todo_v1_DeleteSubtaskRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_monorepo_todo_v1_DeleteSubtaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_DeleteSubtaskRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_monorepo_todo_v1_BatchGetTodosRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_monorepo_todo_v1_BatchGetTodosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_BatchGetTodosRequest_descriptor,
        new java.lang.String[] { "Ids", "ShowDeleted", });
    internal_static_monorepo_todo_v1_BatchGetTodosResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_monorepo_todo_v1_BatchGetTodosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_BatchGetTodosResponse_descriptor,
        new java.lang.String[] { "Todos", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
    monorepo.proto.todo.v1.TodoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
