// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monorepo/todo/v1/todo.proto
// Protobuf Java Version: 4.34.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public final class TodoProto extends com.google.protobuf.GeneratedFile {
  private TodoProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TodoProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_Todo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_Todo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_Todo_Attribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_Todo_Attribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monorepo_todo_v1_SubTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monorepo_todo_v1_SubTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033monorepo/todo/v1/todo.proto\022\020monorepo." +
      "todo.v1\032\037google/protobuf/timestamp.proto" +
      "\032\026google/type/date.proto\"\311\006\n\004Todo\022\016\n\002id\030" +
      "\001 \001(\003R\002id\022\027\n\007user_id\030\002 \001(\003R\006userId\022\024\n\005ti" +
      "tle\030\003 \001(\tR\005title\022 \n\013description\030\004 \001(\tR\013d" +
      "escription\0222\n\005state\030\005 \001(\0162\034.monorepo.tod" +
      "o.v1.Todo.StateR\005state\022;\n\010priority\030\006 \001(\016" +
      "2\037.monorepo.todo.v1.Todo.PriorityR\010prior" +
      "ity\022\037\n\010assignee\030\007 \001(\003H\000R\010assignee\210\001\001\022,\n\010" +
      "due_date\030\010 \001(\0132\021.google.type.DateR\007dueDa" +
      "te\0226\n\tsub_tasks\030\t \003(\0132\031.monorepo.todo.v1" +
      ".SubTaskR\010subTasks\022@\n\nattributes\030\n \003(\0132 " +
      ".monorepo.todo.v1.Todo.AttributeR\nattrib" +
      "utes\022\022\n\004tags\030\013 \003(\tR\004tags\0229\n\ncreated_at\030\014" +
      " \001(\0132\032.google.protobuf.TimestampR\tcreate" +
      "dAt\0229\n\nupdated_at\030\r \001(\0132\032.google.protobu" +
      "f.TimestampR\tupdatedAt\022>\n\ndeleted_at\030\016 \001" +
      "(\0132\032.google.protobuf.TimestampH\001R\tdelete" +
      "dAt\210\001\001\0323\n\tAttribute\022\020\n\003key\030\001 \001(\tR\003key\022\024\n" +
      "\005value\030\002 \001(\tR\005value\":\n\005State\022\025\n\021STATE_UN" +
      "SPECIFIED\020\000\022\013\n\007PENDING\020\001\022\r\n\tCOMPLETED\020\002\"" +
      "O\n\010Priority\022\030\n\024PRIORITY_UNSPECIFIED\020\000\022\007\n" +
      "\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020\003\022\n\n\006URGENT\020\004" +
      "B\013\n\t_assigneeB\r\n\013_deleted_at\"\245\001\n\007SubTask" +
      "\022\016\n\002id\030\001 \001(\003R\002id\022\024\n\005title\030\003 \001(\tR\005title\0229" +
      "\n\ncreated_at\030\005 \001(\0132\032.google.protobuf.Tim" +
      "estampR\tcreatedAt\0229\n\nupdated_at\030\006 \001(\0132\032." +
      "google.protobuf.TimestampR\tupdatedAtB\202\001\n" +
      "\026monorepo.proto.todo.v1B\tTodoProtoP\001Z[gi" +
      "thub.com/yourorg/monorepo/packages/proto" +
      "-gen-go/monorepo/todo/pkg/monorepo/todo/" +
      "v1;todov1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
        });
    internal_static_monorepo_todo_v1_Todo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_monorepo_todo_v1_Todo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_Todo_descriptor,
        new java.lang.String[] { "Id", "UserId", "Title", "Description", "State", "Priority", "Assignee", "DueDate", "SubTasks", "Attributes", "Tags", "CreatedAt", "UpdatedAt", "DeletedAt", });
    internal_static_monorepo_todo_v1_Todo_Attribute_descriptor =
      internal_static_monorepo_todo_v1_Todo_descriptor.getNestedType(0);
    internal_static_monorepo_todo_v1_Todo_Attribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_Todo_Attribute_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_monorepo_todo_v1_SubTask_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_monorepo_todo_v1_SubTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monorepo_todo_v1_SubTask_descriptor,
        new java.lang.String[] { "Id", "Title", "CreatedAt", "UpdatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
