// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: monorepo/order/v1/everything_edition2023.proto

package orderv1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	dayofweek "google.golang.org/genproto/googleapis/type/dayofweek"
	month "google.golang.org/genproto/googleapis/type/month"
	timeofday "google.golang.org/genproto/googleapis/type/timeofday"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EverythingEdition2023_Enum int32

const (
	EverythingEdition2023_ENUM_UNSPECIFIED EverythingEdition2023_Enum = 0
	EverythingEdition2023_ENUM_VALUE_1     EverythingEdition2023_Enum = 1
	EverythingEdition2023_ENUM_VALUE_2     EverythingEdition2023_Enum = 2
)

// Enum value maps for EverythingEdition2023_Enum.
var (
	EverythingEdition2023_Enum_name = map[int32]string{
		0: "ENUM_UNSPECIFIED",
		1: "ENUM_VALUE_1",
		2: "ENUM_VALUE_2",
	}
	EverythingEdition2023_Enum_value = map[string]int32{
		"ENUM_UNSPECIFIED": 0,
		"ENUM_VALUE_1":     1,
		"ENUM_VALUE_2":     2,
	}
)

func (x EverythingEdition2023_Enum) Enum() *EverythingEdition2023_Enum {
	p := new(EverythingEdition2023_Enum)
	*p = x
	return p
}

func (x EverythingEdition2023_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EverythingEdition2023_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_monorepo_order_v1_everything_edition2023_proto_enumTypes[0].Descriptor()
}

func (EverythingEdition2023_Enum) Type() protoreflect.EnumType {
	return &file_monorepo_order_v1_everything_edition2023_proto_enumTypes[0]
}

func (x EverythingEdition2023_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type EverythingEdition2023 struct {
	state                               protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_Int32                    int32                                     `protobuf:"varint,1,opt,name=int32"`
	xxx_hidden_Int64                    int64                                     `protobuf:"varint,3,opt,name=int64"`
	xxx_hidden_Float                    float32                                   `protobuf:"fixed32,11,opt,name=float"`
	xxx_hidden_Double                   float64                                   `protobuf:"fixed64,12,opt,name=double"`
	xxx_hidden_Bool                     bool                                      `protobuf:"varint,13,opt,name=bool"`
	xxx_hidden_String_                  *string                                   `protobuf:"bytes,14,opt,name=string"`
	xxx_hidden_Bytes                    []byte                                    `protobuf:"bytes,15,opt,name=bytes"`
	xxx_hidden_RepeatedInt32            []int32                                   `protobuf:"varint,16,rep,packed,name=repeated_int32,json=repeatedInt32"`
	xxx_hidden_RepeatedInt64            []int64                                   `protobuf:"varint,18,rep,packed,name=repeated_int64,json=repeatedInt64"`
	xxx_hidden_RepeatedFloat            []float32                                 `protobuf:"fixed32,26,rep,packed,name=repeated_float,json=repeatedFloat"`
	xxx_hidden_RepeatedDouble           []float64                                 `protobuf:"fixed64,27,rep,packed,name=repeated_double,json=repeatedDouble"`
	xxx_hidden_RepeatedBool             []bool                                    `protobuf:"varint,28,rep,packed,name=repeated_bool,json=repeatedBool"`
	xxx_hidden_RepeatedString           []string                                  `protobuf:"bytes,29,rep,name=repeated_string,json=repeatedString"`
	xxx_hidden_RepeatedBytes            [][]byte                                  `protobuf:"bytes,30,rep,name=repeated_bytes,json=repeatedBytes"`
	xxx_hidden_Int32Value               *wrapperspb.Int32Value                    `protobuf:"bytes,20,opt,name=int32_value,json=int32Value"`
	xxx_hidden_Int64Value               *wrapperspb.Int64Value                    `protobuf:"bytes,21,opt,name=int64_value,json=int64Value"`
	xxx_hidden_FloatValue               *wrapperspb.FloatValue                    `protobuf:"bytes,22,opt,name=float_value,json=floatValue"`
	xxx_hidden_DoubleValue              *wrapperspb.DoubleValue                   `protobuf:"bytes,23,opt,name=double_value,json=doubleValue"`
	xxx_hidden_BoolValue                *wrapperspb.BoolValue                     `protobuf:"bytes,24,opt,name=bool_value,json=boolValue"`
	xxx_hidden_StringValue              *wrapperspb.StringValue                   `protobuf:"bytes,25,opt,name=string_value,json=stringValue"`
	xxx_hidden_BytesValue               *wrapperspb.BytesValue                    `protobuf:"bytes,31,opt,name=bytes_value,json=bytesValue"`
	xxx_hidden_MapInt32String           map[int32]string                          `protobuf:"bytes,32,rep,name=map_int32_string,json=mapInt32String" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MapInt64String           map[int64]string                          `protobuf:"bytes,34,rep,name=map_int64_string,json=mapInt64String" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MapBoolString            map[bool]string                           `protobuf:"bytes,44,rep,name=map_bool_string,json=mapBoolString" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MapStringString          map[string]string                         `protobuf:"bytes,45,rep,name=map_string_string,json=mapStringString" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MapStringBytes           map[string][]byte                         `protobuf:"bytes,46,rep,name=map_string_bytes,json=mapStringBytes" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Message                  *EverythingEdition2023_Message            `protobuf:"bytes,50,opt,name=message"`
	xxx_hidden_RepeatedMessage          *[]*EverythingEdition2023_Message         `protobuf:"bytes,51,rep,name=repeated_message,json=repeatedMessage"`
	xxx_hidden_MapStringMessage         map[string]*EverythingEdition2023_Message `protobuf:"bytes,52,rep,name=map_string_message,json=mapStringMessage" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Enum                     EverythingEdition2023_Enum                `protobuf:"varint,60,opt,name=enum,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_OptionalEnum             EverythingEdition2023_Enum                `protobuf:"varint,62,opt,name=optional_enum,json=optionalEnum,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_RepeatedEnum             []EverythingEdition2023_Enum              `protobuf:"varint,61,rep,packed,name=repeated_enum,json=repeatedEnum,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_MapStringEnum            map[string]EverythingEdition2023_Enum     `protobuf:"bytes,63,rep,name=map_string_enum,json=mapStringEnum" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_Timestamp                *timestamppb.Timestamp                    `protobuf:"bytes,65,opt,name=timestamp"`
	xxx_hidden_Duration                 *durationpb.Duration                      `protobuf:"bytes,66,opt,name=duration"`
	xxx_hidden_TimeOfDay                *timeofday.TimeOfDay                      `protobuf:"bytes,70,opt,name=time_of_day,json=timeOfDay"`
	xxx_hidden_Date                     *date.Date                                `protobuf:"bytes,71,opt,name=date"`
	xxx_hidden_DayOfWeek                dayofweek.DayOfWeek                       `protobuf:"varint,73,opt,name=day_of_week,json=dayOfWeek,enum=google.type.DayOfWeek"`
	xxx_hidden_Month                    month.Month                               `protobuf:"varint,74,opt,name=month,enum=google.type.Month"`
	xxx_hidden_Oneof                    isEverythingEdition2023_Oneof             `protobuf_oneof:"oneof"`
	xxx_hidden_DeprecatedInt32          int32                                     `protobuf:"varint,90,opt,name=deprecated_int32,json=deprecatedInt32"`
	xxx_hidden_DeprecatedString         *string                                   `protobuf:"bytes,91,opt,name=deprecated_string,json=deprecatedString"`
	xxx_hidden_DeprecatedRepeatedString []string                                  `protobuf:"bytes,92,rep,name=deprecated_repeated_string,json=deprecatedRepeatedString"`
	xxx_hidden_DeprecatedMapStringInt32 map[string]int32                          `protobuf:"bytes,93,rep,name=deprecated_map_string_int32,json=deprecatedMapStringInt32" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	xxx_hidden_DeprecatedEnum           EverythingEdition2023_Enum                `protobuf:"varint,94,opt,name=deprecated_enum,json=deprecatedEnum,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_StrBytes                 *string                                   `protobuf:"bytes,100,opt,name=str_bytes,json=strBytes"`
	xxx_hidden_EnValue                  EverythingEdition2023_Enum                `protobuf:"varint,101,opt,name=en_value,json=enValue,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_ReStringList             []string                                  `protobuf:"bytes,102,rep,name=re_string_list,json=reStringList"`
	xxx_hidden_ReEnumValueList          []EverythingEdition2023_Enum              `protobuf:"varint,107,rep,packed,name=re_enum_value_list,json=reEnumValueList,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_MaStringStringMap        map[string]string                         `protobuf:"bytes,103,rep,name=ma_string_string_map,json=maStringStringMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_MaStringEnumMap          map[string]EverythingEdition2023_Enum     `protobuf:"bytes,104,rep,name=ma_string_enum_map,json=maStringEnumMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=monorepo.order.v1.EverythingEdition2023_Enum"`
	xxx_hidden_MsgBuilder               *EverythingEdition2023_Message            `protobuf:"bytes,105,opt,name=msg_builder,json=msgBuilder"`
	xxx_hidden_MsgOrBuilder             *EverythingEdition2023_Message            `protobuf:"bytes,106,opt,name=msg_or_builder,json=msgOrBuilder"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [2]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *EverythingEdition2023) Reset() {
	*x = EverythingEdition2023{}
	mi := &file_monorepo_order_v1_everything_edition2023_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EverythingEdition2023) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EverythingEdition2023) ProtoMessage() {}

func (x *EverythingEdition2023) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_order_v1_everything_edition2023_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EverythingEdition2023) GetInt32() int32 {
	if x != nil {
		return x.xxx_hidden_Int32
	}
	return 0
}

func (x *EverythingEdition2023) GetInt64() int64 {
	if x != nil {
		return x.xxx_hidden_Int64
	}
	return 0
}

func (x *EverythingEdition2023) GetFloat() float32 {
	if x != nil {
		return x.xxx_hidden_Float
	}
	return 0
}

func (x *EverythingEdition2023) GetDouble() float64 {
	if x != nil {
		return x.xxx_hidden_Double
	}
	return 0
}

func (x *EverythingEdition2023) GetBool() bool {
	if x != nil {
		return x.xxx_hidden_Bool
	}
	return false
}

func (x *EverythingEdition2023) GetString() string {
	if x != nil {
		if x.xxx_hidden_String_ != nil {
			return *x.xxx_hidden_String_
		}
		return ""
	}
	return ""
}

func (x *EverythingEdition2023) GetBytes() []byte {
	if x != nil {
		return x.xxx_hidden_Bytes
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.xxx_hidden_RepeatedInt32
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.xxx_hidden_RepeatedInt64
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.xxx_hidden_RepeatedFloat
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.xxx_hidden_RepeatedDouble
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedBool() []bool {
	if x != nil {
		return x.xxx_hidden_RepeatedBool
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedString() []string {
	if x != nil {
		return x.xxx_hidden_RepeatedString
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.xxx_hidden_RepeatedBytes
	}
	return nil
}

func (x *EverythingEdition2023) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Int32Value
	}
	return nil
}

func (x *EverythingEdition2023) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.xxx_hidden_Int64Value
	}
	return nil
}

func (x *EverythingEdition2023) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.xxx_hidden_FloatValue
	}
	return nil
}

func (x *EverythingEdition2023) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.xxx_hidden_DoubleValue
	}
	return nil
}

func (x *EverythingEdition2023) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_BoolValue
	}
	return nil
}

func (x *EverythingEdition2023) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_StringValue
	}
	return nil
}

func (x *EverythingEdition2023) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_BytesValue
	}
	return nil
}

func (x *EverythingEdition2023) GetMapInt32String() map[int32]string {
	if x != nil {
		return x.xxx_hidden_MapInt32String
	}
	return nil
}

func (x *EverythingEdition2023) GetMapInt64String() map[int64]string {
	if x != nil {
		return x.xxx_hidden_MapInt64String
	}
	return nil
}

func (x *EverythingEdition2023) GetMapBoolString() map[bool]string {
	if x != nil {
		return x.xxx_hidden_MapBoolString
	}
	return nil
}

func (x *EverythingEdition2023) GetMapStringString() map[string]string {
	if x != nil {
		return x.xxx_hidden_MapStringString
	}
	return nil
}

func (x *EverythingEdition2023) GetMapStringBytes() map[string][]byte {
	if x != nil {
		return x.xxx_hidden_MapStringBytes
	}
	return nil
}

func (x *EverythingEdition2023) GetMessage() *EverythingEdition2023_Message {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return nil
}

func (x *EverythingEdition2023) GetRepeatedMessage() []*EverythingEdition2023_Message {
	if x != nil {
		if x.xxx_hidden_RepeatedMessage != nil {
			return *x.xxx_hidden_RepeatedMessage
		}
	}
	return nil
}

func (x *EverythingEdition2023) GetMapStringMessage() map[string]*EverythingEdition2023_Message {
	if x != nil {
		return x.xxx_hidden_MapStringMessage
	}
	return nil
}

func (x *EverythingEdition2023) GetEnum() EverythingEdition2023_Enum {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 29) {
			return x.xxx_hidden_Enum
		}
	}
	return EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) GetOptionalEnum() EverythingEdition2023_Enum {
	if x != nil {
		return x.xxx_hidden_OptionalEnum
	}
	return EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) GetRepeatedEnum() []EverythingEdition2023_Enum {
	if x != nil {
		return x.xxx_hidden_RepeatedEnum
	}
	return nil
}

func (x *EverythingEdition2023) GetMapStringEnum() map[string]EverythingEdition2023_Enum {
	if x != nil {
		return x.xxx_hidden_MapStringEnum
	}
	return nil
}

func (x *EverythingEdition2023) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *EverythingEdition2023) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Duration
	}
	return nil
}

func (x *EverythingEdition2023) GetTimeOfDay() *timeofday.TimeOfDay {
	if x != nil {
		return x.xxx_hidden_TimeOfDay
	}
	return nil
}

func (x *EverythingEdition2023) GetDate() *date.Date {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return nil
}

func (x *EverythingEdition2023) GetDayOfWeek() dayofweek.DayOfWeek {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[1]), 37) {
			return x.xxx_hidden_DayOfWeek
		}
	}
	return dayofweek.DayOfWeek(0)
}

func (x *EverythingEdition2023) GetMonth() month.Month {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[1]), 38) {
			return x.xxx_hidden_Month
		}
	}
	return month.Month(0)
}

func (x *EverythingEdition2023) GetOneofInt32() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofInt32); ok {
			return x.OneofInt32
		}
	}
	return 0
}

func (x *EverythingEdition2023) GetOneofString() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

func (x *EverythingEdition2023) GetOneofEnum() EverythingEdition2023_Enum {
	if x != nil {
		if x, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofEnum); ok {
			return x.OneofEnum
		}
	}
	return EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) GetOneofMessage() *EverythingEdition2023_Message {
	if x != nil {
		if x, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofMessage); ok {
			return x.OneofMessage
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) GetDeprecatedInt32() int32 {
	if x != nil {
		return x.xxx_hidden_DeprecatedInt32
	}
	return 0
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) GetDeprecatedString() string {
	if x != nil {
		if x.xxx_hidden_DeprecatedString != nil {
			return *x.xxx_hidden_DeprecatedString
		}
		return ""
	}
	return ""
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) GetDeprecatedRepeatedString() []string {
	if x != nil {
		return x.xxx_hidden_DeprecatedRepeatedString
	}
	return nil
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) GetDeprecatedMapStringInt32() map[string]int32 {
	if x != nil {
		return x.xxx_hidden_DeprecatedMapStringInt32
	}
	return nil
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) GetDeprecatedEnum() EverythingEdition2023_Enum {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[1]), 44) {
			return x.xxx_hidden_DeprecatedEnum
		}
	}
	return EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) GetStrBytes() string {
	if x != nil {
		if x.xxx_hidden_StrBytes != nil {
			return *x.xxx_hidden_StrBytes
		}
		return ""
	}
	return ""
}

func (x *EverythingEdition2023) GetEnValue() EverythingEdition2023_Enum {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[1]), 46) {
			return x.xxx_hidden_EnValue
		}
	}
	return EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) GetReStringList() []string {
	if x != nil {
		return x.xxx_hidden_ReStringList
	}
	return nil
}

func (x *EverythingEdition2023) GetReEnumValueList() []EverythingEdition2023_Enum {
	if x != nil {
		return x.xxx_hidden_ReEnumValueList
	}
	return nil
}

func (x *EverythingEdition2023) GetMaStringStringMap() map[string]string {
	if x != nil {
		return x.xxx_hidden_MaStringStringMap
	}
	return nil
}

func (x *EverythingEdition2023) GetMaStringEnumMap() map[string]EverythingEdition2023_Enum {
	if x != nil {
		return x.xxx_hidden_MaStringEnumMap
	}
	return nil
}

func (x *EverythingEdition2023) GetMsgBuilder() *EverythingEdition2023_Message {
	if x != nil {
		return x.xxx_hidden_MsgBuilder
	}
	return nil
}

func (x *EverythingEdition2023) GetMsgOrBuilder() *EverythingEdition2023_Message {
	if x != nil {
		return x.xxx_hidden_MsgOrBuilder
	}
	return nil
}

func (x *EverythingEdition2023) SetInt32(v int32) {
	x.xxx_hidden_Int32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 53)
}

func (x *EverythingEdition2023) SetInt64(v int64) {
	x.xxx_hidden_Int64 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 53)
}

func (x *EverythingEdition2023) SetFloat(v float32) {
	x.xxx_hidden_Float = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 53)
}

func (x *EverythingEdition2023) SetDouble(v float64) {
	x.xxx_hidden_Double = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 53)
}

func (x *EverythingEdition2023) SetBool(v bool) {
	x.xxx_hidden_Bool = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 53)
}

func (x *EverythingEdition2023) SetString(v string) {
	x.xxx_hidden_String_ = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 53)
}

func (x *EverythingEdition2023) SetBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Bytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 53)
}

func (x *EverythingEdition2023) SetRepeatedInt32(v []int32) {
	x.xxx_hidden_RepeatedInt32 = v
}

func (x *EverythingEdition2023) SetRepeatedInt64(v []int64) {
	x.xxx_hidden_RepeatedInt64 = v
}

func (x *EverythingEdition2023) SetRepeatedFloat(v []float32) {
	x.xxx_hidden_RepeatedFloat = v
}

func (x *EverythingEdition2023) SetRepeatedDouble(v []float64) {
	x.xxx_hidden_RepeatedDouble = v
}

func (x *EverythingEdition2023) SetRepeatedBool(v []bool) {
	x.xxx_hidden_RepeatedBool = v
}

func (x *EverythingEdition2023) SetRepeatedString(v []string) {
	x.xxx_hidden_RepeatedString = v
}

func (x *EverythingEdition2023) SetRepeatedBytes(v [][]byte) {
	x.xxx_hidden_RepeatedBytes = v
}

func (x *EverythingEdition2023) SetInt32Value(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Int32Value = v
}

func (x *EverythingEdition2023) SetInt64Value(v *wrapperspb.Int64Value) {
	x.xxx_hidden_Int64Value = v
}

func (x *EverythingEdition2023) SetFloatValue(v *wrapperspb.FloatValue) {
	x.xxx_hidden_FloatValue = v
}

func (x *EverythingEdition2023) SetDoubleValue(v *wrapperspb.DoubleValue) {
	x.xxx_hidden_DoubleValue = v
}

func (x *EverythingEdition2023) SetBoolValue(v *wrapperspb.BoolValue) {
	x.xxx_hidden_BoolValue = v
}

func (x *EverythingEdition2023) SetStringValue(v *wrapperspb.StringValue) {
	x.xxx_hidden_StringValue = v
}

func (x *EverythingEdition2023) SetBytesValue(v *wrapperspb.BytesValue) {
	x.xxx_hidden_BytesValue = v
}

func (x *EverythingEdition2023) SetMapInt32String(v map[int32]string) {
	x.xxx_hidden_MapInt32String = v
}

func (x *EverythingEdition2023) SetMapInt64String(v map[int64]string) {
	x.xxx_hidden_MapInt64String = v
}

func (x *EverythingEdition2023) SetMapBoolString(v map[bool]string) {
	x.xxx_hidden_MapBoolString = v
}

func (x *EverythingEdition2023) SetMapStringString(v map[string]string) {
	x.xxx_hidden_MapStringString = v
}

func (x *EverythingEdition2023) SetMapStringBytes(v map[string][]byte) {
	x.xxx_hidden_MapStringBytes = v
}

func (x *EverythingEdition2023) SetMessage(v *EverythingEdition2023_Message) {
	x.xxx_hidden_Message = v
}

func (x *EverythingEdition2023) SetRepeatedMessage(v []*EverythingEdition2023_Message) {
	x.xxx_hidden_RepeatedMessage = &v
}

func (x *EverythingEdition2023) SetMapStringMessage(v map[string]*EverythingEdition2023_Message) {
	x.xxx_hidden_MapStringMessage = v
}

func (x *EverythingEdition2023) SetEnum(v EverythingEdition2023_Enum) {
	x.xxx_hidden_Enum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 29, 53)
}

func (x *EverythingEdition2023) SetOptionalEnum(v EverythingEdition2023_Enum) {
	x.xxx_hidden_OptionalEnum = v
}

func (x *EverythingEdition2023) SetRepeatedEnum(v []EverythingEdition2023_Enum) {
	x.xxx_hidden_RepeatedEnum = v
}

func (x *EverythingEdition2023) SetMapStringEnum(v map[string]EverythingEdition2023_Enum) {
	x.xxx_hidden_MapStringEnum = v
}

func (x *EverythingEdition2023) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *EverythingEdition2023) SetDuration(v *durationpb.Duration) {
	x.xxx_hidden_Duration = v
}

func (x *EverythingEdition2023) SetTimeOfDay(v *timeofday.TimeOfDay) {
	x.xxx_hidden_TimeOfDay = v
}

func (x *EverythingEdition2023) SetDate(v *date.Date) {
	x.xxx_hidden_Date = v
}

func (x *EverythingEdition2023) SetDayOfWeek(v dayofweek.DayOfWeek) {
	x.xxx_hidden_DayOfWeek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 37, 53)
}

func (x *EverythingEdition2023) SetMonth(v month.Month) {
	x.xxx_hidden_Month = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 38, 53)
}

func (x *EverythingEdition2023) SetOneofInt32(v int32) {
	x.xxx_hidden_Oneof = &everythingEdition2023_OneofInt32{v}
}

func (x *EverythingEdition2023) SetOneofString(v string) {
	x.xxx_hidden_Oneof = &everythingEdition2023_OneofString{v}
}

func (x *EverythingEdition2023) SetOneofEnum(v EverythingEdition2023_Enum) {
	x.xxx_hidden_Oneof = &everythingEdition2023_OneofEnum{v}
}

func (x *EverythingEdition2023) SetOneofMessage(v *EverythingEdition2023_Message) {
	if v == nil {
		x.xxx_hidden_Oneof = nil
		return
	}
	x.xxx_hidden_Oneof = &everythingEdition2023_OneofMessage{v}
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) SetDeprecatedInt32(v int32) {
	x.xxx_hidden_DeprecatedInt32 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 40, 53)
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) SetDeprecatedString(v string) {
	x.xxx_hidden_DeprecatedString = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 41, 53)
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) SetDeprecatedRepeatedString(v []string) {
	x.xxx_hidden_DeprecatedRepeatedString = v
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) SetDeprecatedMapStringInt32(v map[string]int32) {
	x.xxx_hidden_DeprecatedMapStringInt32 = v
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) SetDeprecatedEnum(v EverythingEdition2023_Enum) {
	x.xxx_hidden_DeprecatedEnum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 44, 53)
}

func (x *EverythingEdition2023) SetStrBytes(v string) {
	x.xxx_hidden_StrBytes = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 45, 53)
}

func (x *EverythingEdition2023) SetEnValue(v EverythingEdition2023_Enum) {
	x.xxx_hidden_EnValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 46, 53)
}

func (x *EverythingEdition2023) SetReStringList(v []string) {
	x.xxx_hidden_ReStringList = v
}

func (x *EverythingEdition2023) SetReEnumValueList(v []EverythingEdition2023_Enum) {
	x.xxx_hidden_ReEnumValueList = v
}

func (x *EverythingEdition2023) SetMaStringStringMap(v map[string]string) {
	x.xxx_hidden_MaStringStringMap = v
}

func (x *EverythingEdition2023) SetMaStringEnumMap(v map[string]EverythingEdition2023_Enum) {
	x.xxx_hidden_MaStringEnumMap = v
}

func (x *EverythingEdition2023) SetMsgBuilder(v *EverythingEdition2023_Message) {
	x.xxx_hidden_MsgBuilder = v
}

func (x *EverythingEdition2023) SetMsgOrBuilder(v *EverythingEdition2023_Message) {
	x.xxx_hidden_MsgOrBuilder = v
}

func (x *EverythingEdition2023) HasInt32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EverythingEdition2023) HasInt64() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EverythingEdition2023) HasFloat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EverythingEdition2023) HasDouble() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EverythingEdition2023) HasBool() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EverythingEdition2023) HasString() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *EverythingEdition2023) HasBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *EverythingEdition2023) HasInt32Value() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Int32Value != nil
}

func (x *EverythingEdition2023) HasInt64Value() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Int64Value != nil
}

func (x *EverythingEdition2023) HasFloatValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FloatValue != nil
}

func (x *EverythingEdition2023) HasDoubleValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DoubleValue != nil
}

func (x *EverythingEdition2023) HasBoolValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BoolValue != nil
}

func (x *EverythingEdition2023) HasStringValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StringValue != nil
}

func (x *EverythingEdition2023) HasBytesValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BytesValue != nil
}

func (x *EverythingEdition2023) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *EverythingEdition2023) HasEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 29)
}

func (x *EverythingEdition2023) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *EverythingEdition2023) HasDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Duration != nil
}

func (x *EverythingEdition2023) HasTimeOfDay() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TimeOfDay != nil
}

func (x *EverythingEdition2023) HasDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Date != nil
}

func (x *EverythingEdition2023) HasDayOfWeek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 37)
}

func (x *EverythingEdition2023) HasMonth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 38)
}

func (x *EverythingEdition2023) HasOneof() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Oneof != nil
}

func (x *EverythingEdition2023) HasOneofInt32() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofInt32)
	return ok
}

func (x *EverythingEdition2023) HasOneofString() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofString)
	return ok
}

func (x *EverythingEdition2023) HasOneofEnum() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofEnum)
	return ok
}

func (x *EverythingEdition2023) HasOneofMessage() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofMessage)
	return ok
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) HasDeprecatedInt32() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 40)
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) HasDeprecatedString() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 41)
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) HasDeprecatedEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 44)
}

func (x *EverythingEdition2023) HasStrBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 45)
}

func (x *EverythingEdition2023) HasEnValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 46)
}

func (x *EverythingEdition2023) HasMsgBuilder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MsgBuilder != nil
}

func (x *EverythingEdition2023) HasMsgOrBuilder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MsgOrBuilder != nil
}

func (x *EverythingEdition2023) ClearInt32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Int32 = 0
}

func (x *EverythingEdition2023) ClearInt64() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Int64 = 0
}

func (x *EverythingEdition2023) ClearFloat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Float = 0
}

func (x *EverythingEdition2023) ClearDouble() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Double = 0
}

func (x *EverythingEdition2023) ClearBool() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Bool = false
}

func (x *EverythingEdition2023) ClearString() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_String_ = nil
}

func (x *EverythingEdition2023) ClearBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Bytes = nil
}

func (x *EverythingEdition2023) ClearInt32Value() {
	x.xxx_hidden_Int32Value = nil
}

func (x *EverythingEdition2023) ClearInt64Value() {
	x.xxx_hidden_Int64Value = nil
}

func (x *EverythingEdition2023) ClearFloatValue() {
	x.xxx_hidden_FloatValue = nil
}

func (x *EverythingEdition2023) ClearDoubleValue() {
	x.xxx_hidden_DoubleValue = nil
}

func (x *EverythingEdition2023) ClearBoolValue() {
	x.xxx_hidden_BoolValue = nil
}

func (x *EverythingEdition2023) ClearStringValue() {
	x.xxx_hidden_StringValue = nil
}

func (x *EverythingEdition2023) ClearBytesValue() {
	x.xxx_hidden_BytesValue = nil
}

func (x *EverythingEdition2023) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *EverythingEdition2023) ClearEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 29)
	x.xxx_hidden_Enum = EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *EverythingEdition2023) ClearDuration() {
	x.xxx_hidden_Duration = nil
}

func (x *EverythingEdition2023) ClearTimeOfDay() {
	x.xxx_hidden_TimeOfDay = nil
}

func (x *EverythingEdition2023) ClearDate() {
	x.xxx_hidden_Date = nil
}

func (x *EverythingEdition2023) ClearDayOfWeek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 37)
	x.xxx_hidden_DayOfWeek = dayofweek.DayOfWeek_DAY_OF_WEEK_UNSPECIFIED
}

func (x *EverythingEdition2023) ClearMonth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 38)
	x.xxx_hidden_Month = month.Month_MONTH_UNSPECIFIED
}

func (x *EverythingEdition2023) ClearOneof() {
	x.xxx_hidden_Oneof = nil
}

func (x *EverythingEdition2023) ClearOneofInt32() {
	if _, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofInt32); ok {
		x.xxx_hidden_Oneof = nil
	}
}

func (x *EverythingEdition2023) ClearOneofString() {
	if _, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofString); ok {
		x.xxx_hidden_Oneof = nil
	}
}

func (x *EverythingEdition2023) ClearOneofEnum() {
	if _, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofEnum); ok {
		x.xxx_hidden_Oneof = nil
	}
}

func (x *EverythingEdition2023) ClearOneofMessage() {
	if _, ok := x.xxx_hidden_Oneof.(*everythingEdition2023_OneofMessage); ok {
		x.xxx_hidden_Oneof = nil
	}
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) ClearDeprecatedInt32() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 40)
	x.xxx_hidden_DeprecatedInt32 = 0
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) ClearDeprecatedString() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 41)
	x.xxx_hidden_DeprecatedString = nil
}

// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
func (x *EverythingEdition2023) ClearDeprecatedEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 44)
	x.xxx_hidden_DeprecatedEnum = EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) ClearStrBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 45)
	x.xxx_hidden_StrBytes = nil
}

func (x *EverythingEdition2023) ClearEnValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 46)
	x.xxx_hidden_EnValue = EverythingEdition2023_ENUM_UNSPECIFIED
}

func (x *EverythingEdition2023) ClearMsgBuilder() {
	x.xxx_hidden_MsgBuilder = nil
}

func (x *EverythingEdition2023) ClearMsgOrBuilder() {
	x.xxx_hidden_MsgOrBuilder = nil
}

const EverythingEdition2023_Oneof_not_set_case case_EverythingEdition2023_Oneof = 0
const EverythingEdition2023_OneofInt32_case case_EverythingEdition2023_Oneof = 80
const EverythingEdition2023_OneofString_case case_EverythingEdition2023_Oneof = 81
const EverythingEdition2023_OneofEnum_case case_EverythingEdition2023_Oneof = 82
const EverythingEdition2023_OneofMessage_case case_EverythingEdition2023_Oneof = 83

func (x *EverythingEdition2023) WhichOneof() case_EverythingEdition2023_Oneof {
	if x == nil {
		return EverythingEdition2023_Oneof_not_set_case
	}
	switch x.xxx_hidden_Oneof.(type) {
	case *everythingEdition2023_OneofInt32:
		return EverythingEdition2023_OneofInt32_case
	case *everythingEdition2023_OneofString:
		return EverythingEdition2023_OneofString_case
	case *everythingEdition2023_OneofEnum:
		return EverythingEdition2023_OneofEnum_case
	case *everythingEdition2023_OneofMessage:
		return EverythingEdition2023_OneofMessage_case
	default:
		return EverythingEdition2023_Oneof_not_set_case
	}
}

type EverythingEdition2023_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Int32            *int32
	Int64            *int64
	Float            *float32
	Double           *float64
	Bool             *bool
	String           *string
	Bytes            []byte
	RepeatedInt32    []int32
	RepeatedInt64    []int64
	RepeatedFloat    []float32
	RepeatedDouble   []float64
	RepeatedBool     []bool
	RepeatedString   []string
	RepeatedBytes    [][]byte
	Int32Value       *wrapperspb.Int32Value
	Int64Value       *wrapperspb.Int64Value
	FloatValue       *wrapperspb.FloatValue
	DoubleValue      *wrapperspb.DoubleValue
	BoolValue        *wrapperspb.BoolValue
	StringValue      *wrapperspb.StringValue
	BytesValue       *wrapperspb.BytesValue
	MapInt32String   map[int32]string
	MapInt64String   map[int64]string
	MapBoolString    map[bool]string
	MapStringString  map[string]string
	MapStringBytes   map[string][]byte
	Message          *EverythingEdition2023_Message
	RepeatedMessage  []*EverythingEdition2023_Message
	MapStringMessage map[string]*EverythingEdition2023_Message
	Enum             *EverythingEdition2023_Enum
	OptionalEnum     EverythingEdition2023_Enum
	RepeatedEnum     []EverythingEdition2023_Enum
	MapStringEnum    map[string]EverythingEdition2023_Enum
	// wellknown
	Timestamp *timestamppb.Timestamp
	Duration  *durationpb.Duration
	// google/type package
	TimeOfDay *timeofday.TimeOfDay
	Date      *date.Date
	DayOfWeek *dayofweek.DayOfWeek
	Month     *month.Month
	// oneof field

	// Fields of oneof xxx_hidden_Oneof:
	OneofInt32   *int32
	OneofString  *string
	OneofEnum    *EverythingEdition2023_Enum
	OneofMessage *EverythingEdition2023_Message
	// -- end of xxx_hidden_Oneof
	// deprecated field
	//
	// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
	DeprecatedInt32 *int32
	// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
	DeprecatedString *string
	// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
	DeprecatedRepeatedString []string
	// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
	DeprecatedMapStringInt32 map[string]int32
	// Deprecated: Marked as deprecated in monorepo/order/v1/everything_edition2023.proto.
	DeprecatedEnum *EverythingEdition2023_Enum
	// special naming
	StrBytes          *string
	EnValue           *EverythingEdition2023_Enum
	ReStringList      []string
	ReEnumValueList   []EverythingEdition2023_Enum
	MaStringStringMap map[string]string
	MaStringEnumMap   map[string]EverythingEdition2023_Enum
	MsgBuilder        *EverythingEdition2023_Message
	MsgOrBuilder      *EverythingEdition2023_Message
}

func (b0 EverythingEdition2023_builder) Build() *EverythingEdition2023 {
	m0 := &EverythingEdition2023{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Int32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 53)
		x.xxx_hidden_Int32 = *b.Int32
	}
	if b.Int64 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 53)
		x.xxx_hidden_Int64 = *b.Int64
	}
	if b.Float != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 53)
		x.xxx_hidden_Float = *b.Float
	}
	if b.Double != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 53)
		x.xxx_hidden_Double = *b.Double
	}
	if b.Bool != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 53)
		x.xxx_hidden_Bool = *b.Bool
	}
	if b.String != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 53)
		x.xxx_hidden_String_ = b.String
	}
	if b.Bytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 53)
		x.xxx_hidden_Bytes = b.Bytes
	}
	x.xxx_hidden_RepeatedInt32 = b.RepeatedInt32
	x.xxx_hidden_RepeatedInt64 = b.RepeatedInt64
	x.xxx_hidden_RepeatedFloat = b.RepeatedFloat
	x.xxx_hidden_RepeatedDouble = b.RepeatedDouble
	x.xxx_hidden_RepeatedBool = b.RepeatedBool
	x.xxx_hidden_RepeatedString = b.RepeatedString
	x.xxx_hidden_RepeatedBytes = b.RepeatedBytes
	x.xxx_hidden_Int32Value = b.Int32Value
	x.xxx_hidden_Int64Value = b.Int64Value
	x.xxx_hidden_FloatValue = b.FloatValue
	x.xxx_hidden_DoubleValue = b.DoubleValue
	x.xxx_hidden_BoolValue = b.BoolValue
	x.xxx_hidden_StringValue = b.StringValue
	x.xxx_hidden_BytesValue = b.BytesValue
	x.xxx_hidden_MapInt32String = b.MapInt32String
	x.xxx_hidden_MapInt64String = b.MapInt64String
	x.xxx_hidden_MapBoolString = b.MapBoolString
	x.xxx_hidden_MapStringString = b.MapStringString
	x.xxx_hidden_MapStringBytes = b.MapStringBytes
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_RepeatedMessage = &b.RepeatedMessage
	x.xxx_hidden_MapStringMessage = b.MapStringMessage
	if b.Enum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 29, 53)
		x.xxx_hidden_Enum = *b.Enum
	}
	x.xxx_hidden_OptionalEnum = b.OptionalEnum
	x.xxx_hidden_RepeatedEnum = b.RepeatedEnum
	x.xxx_hidden_MapStringEnum = b.MapStringEnum
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Duration = b.Duration
	x.xxx_hidden_TimeOfDay = b.TimeOfDay
	x.xxx_hidden_Date = b.Date
	if b.DayOfWeek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 37, 53)
		x.xxx_hidden_DayOfWeek = *b.DayOfWeek
	}
	if b.Month != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 38, 53)
		x.xxx_hidden_Month = *b.Month
	}
	if b.OneofInt32 != nil {
		x.xxx_hidden_Oneof = &everythingEdition2023_OneofInt32{*b.OneofInt32}
	}
	if b.OneofString != nil {
		x.xxx_hidden_Oneof = &everythingEdition2023_OneofString{*b.OneofString}
	}
	if b.OneofEnum != nil {
		x.xxx_hidden_Oneof = &everythingEdition2023_OneofEnum{*b.OneofEnum}
	}
	if b.OneofMessage != nil {
		x.xxx_hidden_Oneof = &everythingEdition2023_OneofMessage{b.OneofMessage}
	}
	if b.DeprecatedInt32 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 40, 53)
		x.xxx_hidden_DeprecatedInt32 = *b.DeprecatedInt32
	}
	if b.DeprecatedString != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 41, 53)
		x.xxx_hidden_DeprecatedString = b.DeprecatedString
	}
	x.xxx_hidden_DeprecatedRepeatedString = b.DeprecatedRepeatedString
	x.xxx_hidden_DeprecatedMapStringInt32 = b.DeprecatedMapStringInt32
	if b.DeprecatedEnum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 44, 53)
		x.xxx_hidden_DeprecatedEnum = *b.DeprecatedEnum
	}
	if b.StrBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 45, 53)
		x.xxx_hidden_StrBytes = b.StrBytes
	}
	if b.EnValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 46, 53)
		x.xxx_hidden_EnValue = *b.EnValue
	}
	x.xxx_hidden_ReStringList = b.ReStringList
	x.xxx_hidden_ReEnumValueList = b.ReEnumValueList
	x.xxx_hidden_MaStringStringMap = b.MaStringStringMap
	x.xxx_hidden_MaStringEnumMap = b.MaStringEnumMap
	x.xxx_hidden_MsgBuilder = b.MsgBuilder
	x.xxx_hidden_MsgOrBuilder = b.MsgOrBuilder
	return m0
}

type case_EverythingEdition2023_Oneof protoreflect.FieldNumber

func (x case_EverythingEdition2023_Oneof) String() string {
	md := file_monorepo_order_v1_everything_edition2023_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEverythingEdition2023_Oneof interface {
	isEverythingEdition2023_Oneof()
}

type everythingEdition2023_OneofInt32 struct {
	OneofInt32 int32 `protobuf:"varint,80,opt,name=oneof_int32,json=oneofInt32,oneof"`
}

type everythingEdition2023_OneofString struct {
	OneofString string `protobuf:"bytes,81,opt,name=oneof_string,json=oneofString,oneof"`
}

type everythingEdition2023_OneofEnum struct {
	OneofEnum EverythingEdition2023_Enum `protobuf:"varint,82,opt,name=oneof_enum,json=oneofEnum,enum=monorepo.order.v1.EverythingEdition2023_Enum,oneof"`
}

type everythingEdition2023_OneofMessage struct {
	OneofMessage *EverythingEdition2023_Message `protobuf:"bytes,83,opt,name=oneof_message,json=oneofMessage,oneof"`
}

func (*everythingEdition2023_OneofInt32) isEverythingEdition2023_Oneof() {}

func (*everythingEdition2023_OneofString) isEverythingEdition2023_Oneof() {}

func (*everythingEdition2023_OneofEnum) isEverythingEdition2023_Oneof() {}

func (*everythingEdition2023_OneofMessage) isEverythingEdition2023_Oneof() {}

type EverythingEdition2023_Message struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EverythingEdition2023_Message) Reset() {
	*x = EverythingEdition2023_Message{}
	mi := &file_monorepo_order_v1_everything_edition2023_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EverythingEdition2023_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EverythingEdition2023_Message) ProtoMessage() {}

func (x *EverythingEdition2023_Message) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_order_v1_everything_edition2023_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EverythingEdition2023_Message) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *EverythingEdition2023_Message) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *EverythingEdition2023_Message) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *EverythingEdition2023_Message) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EverythingEdition2023_Message) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EverythingEdition2023_Message) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EverythingEdition2023_Message) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *EverythingEdition2023_Message) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type EverythingEdition2023_Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *int64
	Name *string
}

func (b0 EverythingEdition2023_Message_builder) Build() *EverythingEdition2023_Message {
	m0 := &EverythingEdition2023_Message{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

var File_monorepo_order_v1_everything_edition2023_proto protoreflect.FileDescriptor

const file_monorepo_order_v1_everything_edition2023_proto_rawDesc = "" +
	"\n" +
	".monorepo/order/v1/everything_edition2023.proto\x12\x11monorepo.order.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16google/type/date.proto\x1a\x1bgoogle/type/dayofweek.proto\x1a\x17google/type/month.proto\x1a\x1bgoogle/type/timeofday.proto\"\xc7#\n" +
	"\x15EverythingEdition2023\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x03 \x01(\x03R\x05int64\x12\x14\n" +
	"\x05float\x18\v \x01(\x02R\x05float\x12\x16\n" +
	"\x06double\x18\f \x01(\x01R\x06double\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytes\x12%\n" +
	"\x0erepeated_int32\x18\x10 \x03(\x05R\rrepeatedInt32\x12%\n" +
	"\x0erepeated_int64\x18\x12 \x03(\x03R\rrepeatedInt64\x12%\n" +
	"\x0erepeated_float\x18\x1a \x03(\x02R\rrepeatedFloat\x12'\n" +
	"\x0frepeated_double\x18\x1b \x03(\x01R\x0erepeatedDouble\x12#\n" +
	"\rrepeated_bool\x18\x1c \x03(\bR\frepeatedBool\x12'\n" +
	"\x0frepeated_string\x18\x1d \x03(\tR\x0erepeatedString\x12%\n" +
	"\x0erepeated_bytes\x18\x1e \x03(\fR\rrepeatedBytes\x12<\n" +
	"\vint32_value\x18\x14 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12<\n" +
	"\vint64_value\x18\x15 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x12<\n" +
	"\vfloat_value\x18\x16 \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"floatValue\x12?\n" +
	"\fdouble_value\x18\x17 \x01(\v2\x1c.google.protobuf.DoubleValueR\vdoubleValue\x129\n" +
	"\n" +
	"bool_value\x18\x18 \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12?\n" +
	"\fstring_value\x18\x19 \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12<\n" +
	"\vbytes_value\x18\x1f \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValue\x12f\n" +
	"\x10map_int32_string\x18  \x03(\v2<.monorepo.order.v1.EverythingEdition2023.MapInt32StringEntryR\x0emapInt32String\x12f\n" +
	"\x10map_int64_string\x18\" \x03(\v2<.monorepo.order.v1.EverythingEdition2023.MapInt64StringEntryR\x0emapInt64String\x12c\n" +
	"\x0fmap_bool_string\x18, \x03(\v2;.monorepo.order.v1.EverythingEdition2023.MapBoolStringEntryR\rmapBoolString\x12i\n" +
	"\x11map_string_string\x18- \x03(\v2=.monorepo.order.v1.EverythingEdition2023.MapStringStringEntryR\x0fmapStringString\x12f\n" +
	"\x10map_string_bytes\x18. \x03(\v2<.monorepo.order.v1.EverythingEdition2023.MapStringBytesEntryR\x0emapStringBytes\x12J\n" +
	"\amessage\x182 \x01(\v20.monorepo.order.v1.EverythingEdition2023.MessageR\amessage\x12[\n" +
	"\x10repeated_message\x183 \x03(\v20.monorepo.order.v1.EverythingEdition2023.MessageR\x0frepeatedMessage\x12l\n" +
	"\x12map_string_message\x184 \x03(\v2>.monorepo.order.v1.EverythingEdition2023.MapStringMessageEntryR\x10mapStringMessage\x12A\n" +
	"\x04enum\x18< \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\x04enum\x12Y\n" +
	"\roptional_enum\x18> \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumB\x05\xaa\x01\x02\b\x02R\foptionalEnum\x12R\n" +
	"\rrepeated_enum\x18= \x03(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\frepeatedEnum\x12c\n" +
	"\x0fmap_string_enum\x18? \x03(\v2;.monorepo.order.v1.EverythingEdition2023.MapStringEnumEntryR\rmapStringEnum\x128\n" +
	"\ttimestamp\x18A \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18B \x01(\v2\x19.google.protobuf.DurationR\bduration\x126\n" +
	"\vtime_of_day\x18F \x01(\v2\x16.google.type.TimeOfDayR\ttimeOfDay\x12%\n" +
	"\x04date\x18G \x01(\v2\x11.google.type.DateR\x04date\x126\n" +
	"\vday_of_week\x18I \x01(\x0e2\x16.google.type.DayOfWeekR\tdayOfWeek\x12(\n" +
	"\x05month\x18J \x01(\x0e2\x12.google.type.MonthR\x05month\x12!\n" +
	"\voneof_int32\x18P \x01(\x05H\x00R\n" +
	"oneofInt32\x12#\n" +
	"\foneof_string\x18Q \x01(\tH\x00R\voneofString\x12N\n" +
	"\n" +
	"oneof_enum\x18R \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumH\x00R\toneofEnum\x12W\n" +
	"\roneof_message\x18S \x01(\v20.monorepo.order.v1.EverythingEdition2023.MessageH\x00R\foneofMessage\x12-\n" +
	"\x10deprecated_int32\x18Z \x01(\x05B\x02\x18\x01R\x0fdeprecatedInt32\x12/\n" +
	"\x11deprecated_string\x18[ \x01(\tB\x02\x18\x01R\x10deprecatedString\x12@\n" +
	"\x1adeprecated_repeated_string\x18\\ \x03(\tB\x02\x18\x01R\x18deprecatedRepeatedString\x12\x89\x01\n" +
	"\x1bdeprecated_map_string_int32\x18] \x03(\v2F.monorepo.order.v1.EverythingEdition2023.DeprecatedMapStringInt32EntryB\x02\x18\x01R\x18deprecatedMapStringInt32\x12Z\n" +
	"\x0fdeprecated_enum\x18^ \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumB\x02\x18\x01R\x0edeprecatedEnum\x12\x1b\n" +
	"\tstr_bytes\x18d \x01(\tR\bstrBytes\x12H\n" +
	"\ben_value\x18e \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\aenValue\x12$\n" +
	"\x0ere_string_list\x18f \x03(\tR\freStringList\x12Z\n" +
	"\x12re_enum_value_list\x18k \x03(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\x0freEnumValueList\x12p\n" +
	"\x14ma_string_string_map\x18g \x03(\v2?.monorepo.order.v1.EverythingEdition2023.MaStringStringMapEntryR\x11maStringStringMap\x12j\n" +
	"\x12ma_string_enum_map\x18h \x03(\v2=.monorepo.order.v1.EverythingEdition2023.MaStringEnumMapEntryR\x0fmaStringEnumMap\x12Q\n" +
	"\vmsg_builder\x18i \x01(\v20.monorepo.order.v1.EverythingEdition2023.MessageR\n" +
	"msgBuilder\x12V\n" +
	"\x0emsg_or_builder\x18j \x01(\v20.monorepo.order.v1.EverythingEdition2023.MessageR\fmsgOrBuilder\x1aA\n" +
	"\x13MapInt32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MapInt64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12MapBoolStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MapStringBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1au\n" +
	"\x15MapStringMessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.monorepo.order.v1.EverythingEdition2023.MessageR\x05value:\x028\x01\x1ao\n" +
	"\x12MapStringEnumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\x05value:\x028\x01\x1aK\n" +
	"\x1dDeprecatedMapStringInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aD\n" +
	"\x16MaStringStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aq\n" +
	"\x14MaStringEnumMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\x0e2-.monorepo.order.v1.EverythingEdition2023.EnumR\x05value:\x028\x01\x1a-\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x04Enum\x12\x14\n" +
	"\x10ENUM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fENUM_VALUE_1\x10\x01\x12\x10\n" +
	"\fENUM_VALUE_2\x10\x02B\a\n" +
	"\x05oneofB\x87\x01\n" +
	"\x17monorepo.proto.order.v1B\x1aEverythingEdition2023ProtoP\x01ZNgithub.com/yourorg/monorepo/packages/proto-gen-go/proto-order/order/v1;orderv1b\beditionsp\xe8\a"

var file_monorepo_order_v1_everything_edition2023_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monorepo_order_v1_everything_edition2023_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_monorepo_order_v1_everything_edition2023_proto_goTypes = []any{
	(EverythingEdition2023_Enum)(0),       // 0: monorepo.order.v1.EverythingEdition2023.Enum
	(*EverythingEdition2023)(nil),         // 1: monorepo.order.v1.EverythingEdition2023
	nil,                                   // 2: monorepo.order.v1.EverythingEdition2023.MapInt32StringEntry
	nil,                                   // 3: monorepo.order.v1.EverythingEdition2023.MapInt64StringEntry
	nil,                                   // 4: monorepo.order.v1.EverythingEdition2023.MapBoolStringEntry
	nil,                                   // 5: monorepo.order.v1.EverythingEdition2023.MapStringStringEntry
	nil,                                   // 6: monorepo.order.v1.EverythingEdition2023.MapStringBytesEntry
	nil,                                   // 7: monorepo.order.v1.EverythingEdition2023.MapStringMessageEntry
	nil,                                   // 8: monorepo.order.v1.EverythingEdition2023.MapStringEnumEntry
	nil,                                   // 9: monorepo.order.v1.EverythingEdition2023.DeprecatedMapStringInt32Entry
	nil,                                   // 10: monorepo.order.v1.EverythingEdition2023.MaStringStringMapEntry
	nil,                                   // 11: monorepo.order.v1.EverythingEdition2023.MaStringEnumMapEntry
	(*EverythingEdition2023_Message)(nil), // 12: monorepo.order.v1.EverythingEdition2023.Message
	(*wrapperspb.Int32Value)(nil),         // 13: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),         // 14: google.protobuf.Int64Value
	(*wrapperspb.FloatValue)(nil),         // 15: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil),        // 16: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),          // 17: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil),        // 18: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),         // 19: google.protobuf.BytesValue
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),           // 21: google.protobuf.Duration
	(*timeofday.TimeOfDay)(nil),           // 22: google.type.TimeOfDay
	(*date.Date)(nil),                     // 23: google.type.Date
	(dayofweek.DayOfWeek)(0),              // 24: google.type.DayOfWeek
	(month.Month)(0),                      // 25: google.type.Month
}
var file_monorepo_order_v1_everything_edition2023_proto_depIdxs = []int32{
	13, // 0: monorepo.order.v1.EverythingEdition2023.int32_value:type_name -> google.protobuf.Int32Value
	14, // 1: monorepo.order.v1.EverythingEdition2023.int64_value:type_name -> google.protobuf.Int64Value
	15, // 2: monorepo.order.v1.EverythingEdition2023.float_value:type_name -> google.protobuf.FloatValue
	16, // 3: monorepo.order.v1.EverythingEdition2023.double_value:type_name -> google.protobuf.DoubleValue
	17, // 4: monorepo.order.v1.EverythingEdition2023.bool_value:type_name -> google.protobuf.BoolValue
	18, // 5: monorepo.order.v1.EverythingEdition2023.string_value:type_name -> google.protobuf.StringValue
	19, // 6: monorepo.order.v1.EverythingEdition2023.bytes_value:type_name -> google.protobuf.BytesValue
	2,  // 7: monorepo.order.v1.EverythingEdition2023.map_int32_string:type_name -> monorepo.order.v1.EverythingEdition2023.MapInt32StringEntry
	3,  // 8: monorepo.order.v1.EverythingEdition2023.map_int64_string:type_name -> monorepo.order.v1.EverythingEdition2023.MapInt64StringEntry
	4,  // 9: monorepo.order.v1.EverythingEdition2023.map_bool_string:type_name -> monorepo.order.v1.EverythingEdition2023.MapBoolStringEntry
	5,  // 10: monorepo.order.v1.EverythingEdition2023.map_string_string:type_name -> monorepo.order.v1.EverythingEdition2023.MapStringStringEntry
	6,  // 11: monorepo.order.v1.EverythingEdition2023.map_string_bytes:type_name -> monorepo.order.v1.EverythingEdition2023.MapStringBytesEntry
	12, // 12: monorepo.order.v1.EverythingEdition2023.message:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	12, // 13: monorepo.order.v1.EverythingEdition2023.repeated_message:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	7,  // 14: monorepo.order.v1.EverythingEdition2023.map_string_message:type_name -> monorepo.order.v1.EverythingEdition2023.MapStringMessageEntry
	0,  // 15: monorepo.order.v1.EverythingEdition2023.enum:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	0,  // 16: monorepo.order.v1.EverythingEdition2023.optional_enum:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	0,  // 17: monorepo.order.v1.EverythingEdition2023.repeated_enum:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	8,  // 18: monorepo.order.v1.EverythingEdition2023.map_string_enum:type_name -> monorepo.order.v1.EverythingEdition2023.MapStringEnumEntry
	20, // 19: monorepo.order.v1.EverythingEdition2023.timestamp:type_name -> google.protobuf.Timestamp
	21, // 20: monorepo.order.v1.EverythingEdition2023.duration:type_name -> google.protobuf.Duration
	22, // 21: monorepo.order.v1.EverythingEdition2023.time_of_day:type_name -> google.type.TimeOfDay
	23, // 22: monorepo.order.v1.EverythingEdition2023.date:type_name -> google.type.Date
	24, // 23: monorepo.order.v1.EverythingEdition2023.day_of_week:type_name -> google.type.DayOfWeek
	25, // 24: monorepo.order.v1.EverythingEdition2023.month:type_name -> google.type.Month
	0,  // 25: monorepo.order.v1.EverythingEdition2023.oneof_enum:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	12, // 26: monorepo.order.v1.EverythingEdition2023.oneof_message:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	9,  // 27: monorepo.order.v1.EverythingEdition2023.deprecated_map_string_int32:type_name -> monorepo.order.v1.EverythingEdition2023.DeprecatedMapStringInt32Entry
	0,  // 28: monorepo.order.v1.EverythingEdition2023.deprecated_enum:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	0,  // 29: monorepo.order.v1.EverythingEdition2023.en_value:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	0,  // 30: monorepo.order.v1.EverythingEdition2023.re_enum_value_list:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	10, // 31: monorepo.order.v1.EverythingEdition2023.ma_string_string_map:type_name -> monorepo.order.v1.EverythingEdition2023.MaStringStringMapEntry
	11, // 32: monorepo.order.v1.EverythingEdition2023.ma_string_enum_map:type_name -> monorepo.order.v1.EverythingEdition2023.MaStringEnumMapEntry
	12, // 33: monorepo.order.v1.EverythingEdition2023.msg_builder:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	12, // 34: monorepo.order.v1.EverythingEdition2023.msg_or_builder:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	12, // 35: monorepo.order.v1.EverythingEdition2023.MapStringMessageEntry.value:type_name -> monorepo.order.v1.EverythingEdition2023.Message
	0,  // 36: monorepo.order.v1.EverythingEdition2023.MapStringEnumEntry.value:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	0,  // 37: monorepo.order.v1.EverythingEdition2023.MaStringEnumMapEntry.value:type_name -> monorepo.order.v1.EverythingEdition2023.Enum
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_monorepo_order_v1_everything_edition2023_proto_init() }
func file_monorepo_order_v1_everything_edition2023_proto_init() {
	if File_monorepo_order_v1_everything_edition2023_proto != nil {
		return
	}
	file_monorepo_order_v1_everything_edition2023_proto_msgTypes[0].OneofWrappers = []any{
		(*everythingEdition2023_OneofInt32)(nil),
		(*everythingEdition2023_OneofString)(nil),
		(*everythingEdition2023_OneofEnum)(nil),
		(*everythingEdition2023_OneofMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monorepo_order_v1_everything_edition2023_proto_rawDesc), len(file_monorepo_order_v1_everything_edition2023_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monorepo_order_v1_everything_edition2023_proto_goTypes,
		DependencyIndexes: file_monorepo_order_v1_everything_edition2023_proto_depIdxs,
		EnumInfos:         file_monorepo_order_v1_everything_edition2023_proto_enumTypes,
		MessageInfos:      file_monorepo_order_v1_everything_edition2023_proto_msgTypes,
	}.Build()
	File_monorepo_order_v1_everything_edition2023_proto = out.File
	file_monorepo_order_v1_everything_edition2023_proto_goTypes = nil
	file_monorepo_order_v1_everything_edition2023_proto_depIdxs = nil
}
