// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order/v1/everything_proto2.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.order.v1;

@com.google.protobuf.Generated
public final class EverythingProto2Proto extends com.google.protobuf.GeneratedFile {
  private EverythingProto2Proto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "EverythingProto2Proto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapInt32StringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapInt32StringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapInt64StringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapInt64StringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapBoolStringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapBoolStringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapStringStringEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapStringStringEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapStringBytesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapStringBytesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapStringMessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapStringMessageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MapStringEnumEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MapStringEnumEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_DeprecatedMapStringInt32Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_DeprecatedMapStringInt32Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MaStringStringMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MaStringStringMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_MaStringEnumMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_MaStringEnumMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_EverythingProto2_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_EverythingProto2_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n order/v1/everything_proto2.proto\022\010orde" +
      "r.v1\032\037google/protobuf/timestamp.proto\032\036g" +
      "oogle/protobuf/duration.proto\032\036google/pr" +
      "otobuf/wrappers.proto\032\033google/type/timeo" +
      "fday.proto\032\026google/type/date.proto\032\033goog" +
      "le/type/dayofweek.proto\032\027google/type/mon" +
      "th.proto\"\334 \n\020EverythingProto2\022\024\n\005int32\030\001" +
      " \002(\005R\005int32\022\024\n\005int64\030\003 \002(\003R\005int64\022\024\n\005flo" +
      "at\030\013 \002(\002R\005float\022\026\n\006double\030\014 \002(\001R\006double\022" +
      "\022\n\004bool\030\r \002(\010R\004bool\022\026\n\006string\030\016 \002(\tR\006str" +
      "ing\022\024\n\005bytes\030\017 \002(\014R\005bytes\022%\n\016repeated_in" +
      "t32\030\020 \003(\005R\rrepeatedInt32\022%\n\016repeated_int" +
      "64\030\022 \003(\003R\rrepeatedInt64\022%\n\016repeated_floa" +
      "t\030\032 \003(\002R\rrepeatedFloat\022\'\n\017repeated_doubl" +
      "e\030\033 \003(\001R\016repeatedDouble\022#\n\rrepeated_bool" +
      "\030\034 \003(\010R\014repeatedBool\022\'\n\017repeated_string\030" +
      "\035 \003(\tR\016repeatedString\022%\n\016repeated_bytes\030" +
      "\036 \003(\014R\rrepeatedBytes\022<\n\013int32_value\030\024 \002(" +
      "\0132\033.google.protobuf.Int32ValueR\nint32Val" +
      "ue\022<\n\013int64_value\030\025 \002(\0132\033.google.protobu" +
      "f.Int64ValueR\nint64Value\022<\n\013float_value\030" +
      "\026 \002(\0132\033.google.protobuf.FloatValueR\nfloa" +
      "tValue\022?\n\014double_value\030\027 \002(\0132\034.google.pr" +
      "otobuf.DoubleValueR\013doubleValue\0229\n\nbool_" +
      "value\030\030 \002(\0132\032.google.protobuf.BoolValueR" +
      "\tboolValue\022?\n\014string_value\030\031 \002(\0132\034.googl" +
      "e.protobuf.StringValueR\013stringValue\022<\n\013b" +
      "ytes_value\030\037 \002(\0132\033.google.protobuf.Bytes" +
      "ValueR\nbytesValue\022X\n\020map_int32_string\030  " +
      "\003(\0132..order.v1.EverythingProto2.MapInt32" +
      "StringEntryR\016mapInt32String\022X\n\020map_int64" +
      "_string\030\" \003(\0132..order.v1.EverythingProto" +
      "2.MapInt64StringEntryR\016mapInt64String\022U\n" +
      "\017map_bool_string\030, \003(\0132-.order.v1.Everyt" +
      "hingProto2.MapBoolStringEntryR\rmapBoolSt" +
      "ring\022[\n\021map_string_string\030- \003(\0132/.order." +
      "v1.EverythingProto2.MapStringStringEntry" +
      "R\017mapStringString\022X\n\020map_string_bytes\030. " +
      "\003(\0132..order.v1.EverythingProto2.MapStrin" +
      "gBytesEntryR\016mapStringBytes\022<\n\007message\0302" +
      " \002(\0132\".order.v1.EverythingProto2.Message" +
      "R\007message\022M\n\020repeated_message\0303 \003(\0132\".or" +
      "der.v1.EverythingProto2.MessageR\017repeate" +
      "dMessage\022^\n\022map_string_message\0304 \003(\01320.o" +
      "rder.v1.EverythingProto2.MapStringMessag" +
      "eEntryR\020mapStringMessage\0223\n\004enum\030< \002(\0162\037" +
      ".order.v1.EverythingProto2.EnumR\004enum\022D\n" +
      "\roptional_enum\030> \001(\0162\037.order.v1.Everythi" +
      "ngProto2.EnumR\014optionalEnum\022D\n\rrepeated_" +
      "enum\030= \003(\0162\037.order.v1.EverythingProto2.E" +
      "numR\014repeatedEnum\022U\n\017map_string_enum\030? \003" +
      "(\0132-.order.v1.EverythingProto2.MapString" +
      "EnumEntryR\rmapStringEnum\0228\n\ttimestamp\030A " +
      "\002(\0132\032.google.protobuf.TimestampR\ttimesta" +
      "mp\0225\n\010duration\030B \002(\0132\031.google.protobuf.D" +
      "urationR\010duration\0226\n\013time_of_day\030F \002(\0132\026" +
      ".google.type.TimeOfDayR\ttimeOfDay\022%\n\004dat" +
      "e\030G \002(\0132\021.google.type.DateR\004date\0226\n\013day_" +
      "of_week\030I \002(\0162\026.google.type.DayOfWeekR\td" +
      "ayOfWeek\022(\n\005month\030J \002(\0162\022.google.type.Mo" +
      "nthR\005month\022!\n\013oneof_int32\030P \001(\005H\000R\noneof" +
      "Int32\022#\n\014oneof_string\030Q \001(\tH\000R\013oneofStri" +
      "ng\022@\n\noneof_enum\030R \001(\0162\037.order.v1.Everyt" +
      "hingProto2.EnumH\000R\toneofEnum\022I\n\roneof_me" +
      "ssage\030S \001(\0132\".order.v1.EverythingProto2." +
      "MessageH\000R\014oneofMessage\022-\n\020deprecated_in" +
      "t32\030Z \002(\005B\002\030\001R\017deprecatedInt32\022/\n\021deprec" +
      "ated_string\030[ \002(\tB\002\030\001R\020deprecatedString\022" +
      "@\n\032deprecated_repeated_string\030\\ \003(\tB\002\030\001R" +
      "\030deprecatedRepeatedString\022{\n\033deprecated_" +
      "map_string_int32\030] \003(\01328.order.v1.Everyt" +
      "hingProto2.DeprecatedMapStringInt32Entry" +
      "B\002\030\001R\030deprecatedMapStringInt32\022L\n\017deprec" +
      "ated_enum\030^ \002(\0162\037.order.v1.EverythingPro" +
      "to2.EnumB\002\030\001R\016deprecatedEnum\022\033\n\tstr_byte" +
      "s\030d \002(\tR\010strBytes\022:\n\010en_value\030e \002(\0162\037.or" +
      "der.v1.EverythingProto2.EnumR\007enValue\022$\n" +
      "\016re_string_list\030f \003(\tR\014reStringList\022L\n\022r" +
      "e_enum_value_list\030k \003(\0162\037.order.v1.Every" +
      "thingProto2.EnumR\017reEnumValueList\022b\n\024ma_" +
      "string_string_map\030g \003(\01321.order.v1.Every" +
      "thingProto2.MaStringStringMapEntryR\021maSt" +
      "ringStringMap\022\\\n\022ma_string_enum_map\030h \003(" +
      "\0132/.order.v1.EverythingProto2.MaStringEn" +
      "umMapEntryR\017maStringEnumMap\022C\n\013msg_build" +
      "er\030i \002(\0132\".order.v1.EverythingProto2.Mes" +
      "sageR\nmsgBuilder\022H\n\016msg_or_builder\030j \002(\013" +
      "2\".order.v1.EverythingProto2.MessageR\014ms" +
      "gOrBuilder\032A\n\023MapInt32StringEntry\022\020\n\003key" +
      "\030\001 \001(\005R\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032A\n" +
      "\023MapInt64StringEntry\022\020\n\003key\030\001 \001(\003R\003key\022\024" +
      "\n\005value\030\002 \001(\tR\005value:\0028\001\032@\n\022MapBoolStrin" +
      "gEntry\022\020\n\003key\030\001 \001(\010R\003key\022\024\n\005value\030\002 \001(\tR" +
      "\005value:\0028\001\032B\n\024MapStringStringEntry\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032A" +
      "\n\023MapStringBytesEntry\022\020\n\003key\030\001 \001(\tR\003key\022" +
      "\024\n\005value\030\002 \001(\014R\005value:\0028\001\032g\n\025MapStringMe" +
      "ssageEntry\022\020\n\003key\030\001 \001(\tR\003key\0228\n\005value\030\002 " +
      "\001(\0132\".order.v1.EverythingProto2.MessageR" +
      "\005value:\0028\001\032a\n\022MapStringEnumEntry\022\020\n\003key\030" +
      "\001 \001(\tR\003key\0225\n\005value\030\002 \001(\0162\037.order.v1.Eve" +
      "rythingProto2.EnumR\005value:\0028\001\032K\n\035Depreca" +
      "tedMapStringInt32Entry\022\020\n\003key\030\001 \001(\tR\003key" +
      "\022\024\n\005value\030\002 \001(\005R\005value:\0028\001\032D\n\026MaStringSt" +
      "ringMapEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030" +
      "\002 \001(\tR\005value:\0028\001\032c\n\024MaStringEnumMapEntry" +
      "\022\020\n\003key\030\001 \001(\tR\003key\0225\n\005value\030\002 \001(\0162\037.orde" +
      "r.v1.EverythingProto2.EnumR\005value:\0028\001\032-\n" +
      "\007Message\022\016\n\002id\030\001 \001(\003R\002id\022\022\n\004name\030\002 \001(\tR\004" +
      "name\"@\n\004Enum\022\024\n\020ENUM_UNSPECIFIED\020\000\022\020\n\014EN" +
      "UM_VALUE_1\020\001\022\020\n\014ENUM_VALUE_2\020\002B\007\n\005oneofB" +
      "v\n\027monorepo.proto.order.v1B\025EverythingPr" +
      "oto2ProtoP\001ZBgithub.com/yourorg/monorepo" +
      "/packages/proto-gen-go/order/v1;orderv1"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.type.TimeOfDayProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
          com.google.type.DayOfWeekProto.getDescriptor(),
          com.google.type.MonthProto.getDescriptor(),
        });
    internal_static_order_v1_EverythingProto2_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_order_v1_EverythingProto2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_descriptor,
        new java.lang.String[] { "Int32", "Int64", "Float", "Double", "Bool", "String", "Bytes", "RepeatedInt32", "RepeatedInt64", "RepeatedFloat", "RepeatedDouble", "RepeatedBool", "RepeatedString", "RepeatedBytes", "Int32Value", "Int64Value", "FloatValue", "DoubleValue", "BoolValue", "StringValue", "BytesValue", "MapInt32String", "MapInt64String", "MapBoolString", "MapStringString", "MapStringBytes", "Message", "RepeatedMessage", "MapStringMessage", "Enum", "OptionalEnum", "RepeatedEnum", "MapStringEnum", "Timestamp", "Duration", "TimeOfDay", "Date", "DayOfWeek", "Month", "OneofInt32", "OneofString", "OneofEnum", "OneofMessage", "DeprecatedInt32", "DeprecatedString", "DeprecatedRepeatedString", "DeprecatedMapStringInt32", "DeprecatedEnum", "StrBytes", "EnValue", "ReStringList", "ReEnumValueList", "MaStringStringMap", "MaStringEnumMap", "MsgBuilder", "MsgOrBuilder", "Oneof", });
    internal_static_order_v1_EverythingProto2_MapInt32StringEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(0);
    internal_static_order_v1_EverythingProto2_MapInt32StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapInt32StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapInt64StringEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(1);
    internal_static_order_v1_EverythingProto2_MapInt64StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapInt64StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapBoolStringEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(2);
    internal_static_order_v1_EverythingProto2_MapBoolStringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapBoolStringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapStringStringEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(3);
    internal_static_order_v1_EverythingProto2_MapStringStringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapStringStringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapStringBytesEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(4);
    internal_static_order_v1_EverythingProto2_MapStringBytesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapStringBytesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapStringMessageEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(5);
    internal_static_order_v1_EverythingProto2_MapStringMessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapStringMessageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MapStringEnumEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(6);
    internal_static_order_v1_EverythingProto2_MapStringEnumEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MapStringEnumEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_DeprecatedMapStringInt32Entry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(7);
    internal_static_order_v1_EverythingProto2_DeprecatedMapStringInt32Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_DeprecatedMapStringInt32Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MaStringStringMapEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(8);
    internal_static_order_v1_EverythingProto2_MaStringStringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MaStringStringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_MaStringEnumMapEntry_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(9);
    internal_static_order_v1_EverythingProto2_MaStringEnumMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_MaStringEnumMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_order_v1_EverythingProto2_Message_descriptor =
      internal_static_order_v1_EverythingProto2_descriptor.getNestedType(10);
    internal_static_order_v1_EverythingProto2_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_EverythingProto2_Message_descriptor,
        new java.lang.String[] { "Id", "Name", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.type.TimeOfDayProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
    com.google.type.DayOfWeekProto.getDescriptor();
    com.google.type.MonthProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
