// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order/v1/order.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.order.v1;

@com.google.protobuf.Generated
public final class Order extends com.google.protobuf.GeneratedFile {
  private Order() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "Order");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_OrderModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_OrderModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_OrderModel_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_order_v1_OrderModel_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024order/v1/order.proto\022\010order.v1\032\037google" +
      "/protobuf/timestamp.proto\"\226\002\n\nOrderModel" +
      "\022\016\n\002id\030\001 \001(\003R\002id\022\031\n\010item_ids\030\002 \003(\003R\007item" +
      "Ids\022\035\n\nitem_names\030\003 \003(\tR\titemNames\022D\n\nat" +
      "tributes\030\004 \003(\0132$.order.v1.OrderModel.Att" +
      "ributesEntryR\nattributes\0229\n\ncreated_at\030\005" +
      " \001(\0132\032.google.protobuf.TimestampR\tcreate" +
      "dAt\032=\n\017AttributesEntry\022\020\n\003key\030\001 \001(\tR\003key" +
      "\022\024\n\005value\030\002 \001(\tR\005value:\0028\001B_\n\027monorepo.p" +
      "roto.order.v1P\001ZBgithub.com/yourorg/mono" +
      "repo/packages/proto-gen-go/order/v1;orde" +
      "rv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_order_v1_OrderModel_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_order_v1_OrderModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_OrderModel_descriptor,
        new java.lang.String[] { "Id", "ItemIds", "ItemNames", "Attributes", "CreatedAt", });
    internal_static_order_v1_OrderModel_AttributesEntry_descriptor =
      internal_static_order_v1_OrderModel_descriptor.getNestedType(0);
    internal_static_order_v1_OrderModel_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_order_v1_OrderModel_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
