// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order/v1/order.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.order.v1;

@com.google.protobuf.Generated
public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.Order)
    com.google.protobuf.MessageOrBuilder {
}
