// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public interface DeleteProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.DeleteProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();
}
