// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public interface ListProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.ListProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product.v1.Product products = 1 [json_name = "products"];</code>
   */
  java.util.List<monorepo.proto.product.v1.Product> 
      getProductsList();
  /**
   * <code>repeated .product.v1.Product products = 1 [json_name = "products"];</code>
   */
  monorepo.proto.product.v1.Product getProducts(int index);
  /**
   * <code>repeated .product.v1.Product products = 1 [json_name = "products"];</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .product.v1.Product products = 1 [json_name = "products"];</code>
   */
  java.util.List<? extends monorepo.proto.product.v1.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .product.v1.Product products = 1 [json_name = "products"];</code>
   */
  monorepo.proto.product.v1.ProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>int32 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  int getTotal();
}
