// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public final class ProductServiceOuterClass extends com.google.protobuf.GeneratedFile {
  private ProductServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ProductServiceOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_product_v1_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_product_v1_GetProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n product/v1/product_service.proto\022\nprod" +
      "uct.v1\032\030product/v1/product.proto\"#\n\021GetP" +
      "roductRequest\022\016\n\002id\030\001 \001(\tR\002id\"C\n\022GetProd" +
      "uctResponse\022-\n\007product\030\001 \001(\0132\023.product.v" +
      "1.ProductR\007product2_\n\016ProductService\022M\n\n" +
      "GetProduct\022\035.product.v1.GetProductReques" +
      "t\032\036.product.v1.GetProductResponse\"\000Be\n\031m" +
      "onorepo.proto.product.v1P\001ZFgithub.com/y" +
      "ourorg/monorepo/packages/proto-gen-go/pr" +
      "oduct/v1;productv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          monorepo.proto.product.v1.ProductOuterClass.getDescriptor(),
        });
    internal_static_product_v1_GetProductRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_product_v1_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_product_v1_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_product_v1_GetProductResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_product_v1_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_product_v1_GetProductResponse_descriptor,
        new java.lang.String[] { "Product", });
    descriptor.resolveAllFeaturesImmutable();
    monorepo.proto.product.v1.ProductOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
