// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public interface CreateProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.CreateProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 3 [json_name = "price"];</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 stock = 4 [json_name = "stock"];</code>
   * @return The stock.
   */
  int getStock();

  /**
   * <code>string category = 5 [json_name = "category"];</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 5 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
