// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public interface CreateProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.CreateProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.product.v1.Product product = 1 [json_name = "product"];</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.product.v1.Product product = 1 [json_name = "product"];</code>
   * @return The product.
   */
  monorepo.proto.product.v1.Product getProduct();
  /**
   * <code>.product.v1.Product product = 1 [json_name = "product"];</code>
   */
  monorepo.proto.product.v1.ProductOrBuilder getProductOrBuilder();
}
