// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product/v1/product_service.proto
// Protobuf Java Version: 4.33.0

package monorepo.proto.product.v1;

@com.google.protobuf.Generated
public interface ListProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.ListProductsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 page_size = 2 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 3 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
