// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: monorepo/todo/v1/todo_service.proto

package todov1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTodosRequest_OrderBy_Field int32

const (
	ListTodosRequest_OrderBy_FIELD_UNSPECIFIED ListTodosRequest_OrderBy_Field = 0
	ListTodosRequest_OrderBy_CREATED_AT        ListTodosRequest_OrderBy_Field = 1
	ListTodosRequest_OrderBy_DUE_DATE          ListTodosRequest_OrderBy_Field = 2
	ListTodosRequest_OrderBy_PRIORITY          ListTodosRequest_OrderBy_Field = 3
)

// Enum value maps for ListTodosRequest_OrderBy_Field.
var (
	ListTodosRequest_OrderBy_Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "CREATED_AT",
		2: "DUE_DATE",
		3: "PRIORITY",
	}
	ListTodosRequest_OrderBy_Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"CREATED_AT":        1,
		"DUE_DATE":          2,
		"PRIORITY":          3,
	}
)

func (x ListTodosRequest_OrderBy_Field) Enum() *ListTodosRequest_OrderBy_Field {
	p := new(ListTodosRequest_OrderBy_Field)
	*p = x
	return p
}

func (x ListTodosRequest_OrderBy_Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListTodosRequest_OrderBy_Field) Descriptor() protoreflect.EnumDescriptor {
	return file_monorepo_todo_v1_todo_service_proto_enumTypes[0].Descriptor()
}

func (ListTodosRequest_OrderBy_Field) Type() protoreflect.EnumType {
	return &file_monorepo_todo_v1_todo_service_proto_enumTypes[0]
}

func (x ListTodosRequest_OrderBy_Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CreateTodoRequest struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_UserId      int64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Title       string                   `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_Description *string                  `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
	xxx_hidden_State       Todo_State               `protobuf:"varint,4,opt,name=state,proto3,enum=monorepo.todo.v1.Todo_State,oneof"`
	xxx_hidden_Priority    Todo_Priority            `protobuf:"varint,5,opt,name=priority,proto3,enum=monorepo.todo.v1.Todo_Priority,oneof"`
	xxx_hidden_Assignee    int64                    `protobuf:"varint,6,opt,name=assignee,proto3,oneof"`
	xxx_hidden_DueDate     *date.Date               `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3,oneof"`
	xxx_hidden_SubTasks    *[]*CreateSubtaskRequest `protobuf:"bytes,8,rep,name=sub_tasks,json=subTasks,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTodoRequest) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateTodoRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CreateTodoRequest) GetState() Todo_State {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return Todo_STATE_UNSPECIFIED
}

func (x *CreateTodoRequest) GetPriority() Todo_Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Priority
		}
	}
	return Todo_PRIORITY_UNSPECIFIED
}

func (x *CreateTodoRequest) GetAssignee() int64 {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return 0
}

func (x *CreateTodoRequest) GetDueDate() *date.Date {
	if x != nil {
		return x.xxx_hidden_DueDate
	}
	return nil
}

func (x *CreateTodoRequest) GetSubTasks() []*CreateSubtaskRequest {
	if x != nil {
		if x.xxx_hidden_SubTasks != nil {
			return *x.xxx_hidden_SubTasks
		}
	}
	return nil
}

func (x *CreateTodoRequest) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *CreateTodoRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *CreateTodoRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *CreateTodoRequest) SetState(v Todo_State) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *CreateTodoRequest) SetPriority(v Todo_Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *CreateTodoRequest) SetAssignee(v int64) {
	x.xxx_hidden_Assignee = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *CreateTodoRequest) SetDueDate(v *date.Date) {
	x.xxx_hidden_DueDate = v
}

func (x *CreateTodoRequest) SetSubTasks(v []*CreateSubtaskRequest) {
	x.xxx_hidden_SubTasks = &v
}

func (x *CreateTodoRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateTodoRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateTodoRequest) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateTodoRequest) HasAssignee() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CreateTodoRequest) HasDueDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DueDate != nil
}

func (x *CreateTodoRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *CreateTodoRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = Todo_STATE_UNSPECIFIED
}

func (x *CreateTodoRequest) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Priority = Todo_PRIORITY_UNSPECIFIED
}

func (x *CreateTodoRequest) ClearAssignee() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Assignee = 0
}

func (x *CreateTodoRequest) ClearDueDate() {
	x.xxx_hidden_DueDate = nil
}

type CreateTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId      int64
	Title       string
	Description *string
	State       *Todo_State
	Priority    *Todo_Priority
	Assignee    *int64
	DueDate     *date.Date
	SubTasks    []*CreateSubtaskRequest
}

func (b0 CreateTodoRequest_builder) Build() *CreateTodoRequest {
	m0 := &CreateTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Title = b.Title
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Description = b.Description
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_State = *b.State
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Priority = *b.Priority
	}
	if b.Assignee != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Assignee = *b.Assignee
	}
	x.xxx_hidden_DueDate = b.DueDate
	x.xxx_hidden_SubTasks = &b.SubTasks
	return m0
}

// Request message for GetTodo
type GetTodoRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_ShowDeleted bool                   `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTodoRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *GetTodoRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *GetTodoRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *GetTodoRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetTodoRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetTodoRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ShowDeleted = false
}

type GetTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
	// default to true if not set
	ShowDeleted *bool
}

func (b0 GetTodoRequest_builder) Build() *GetTodoRequest {
	m0 := &GetTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

// Request message for ListTodos
type ListTodosRequest struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_PageSize    int32                        `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3"`
	xxx_hidden_PageToken   string                       `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3"`
	xxx_hidden_UserId      int64                        `protobuf:"varint,3,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Filter      *ListTodosRequest_Filter     `protobuf:"bytes,4,opt,name=filter,proto3,oneof"`
	xxx_hidden_OrderBy     *[]*ListTodosRequest_OrderBy `protobuf:"bytes,5,rep,name=order_by,json=orderBy,proto3"`
	xxx_hidden_ShowDeleted bool                         `protobuf:"varint,6,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ListTodosRequest) GetPageToken() string {
	if x != nil {
		return x.xxx_hidden_PageToken
	}
	return ""
}

func (x *ListTodosRequest) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *ListTodosRequest) GetFilter() *ListTodosRequest_Filter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *ListTodosRequest) GetOrderBy() []*ListTodosRequest_OrderBy {
	if x != nil {
		if x.xxx_hidden_OrderBy != nil {
			return *x.xxx_hidden_OrderBy
		}
	}
	return nil
}

func (x *ListTodosRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *ListTodosRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
}

func (x *ListTodosRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = v
}

func (x *ListTodosRequest) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *ListTodosRequest) SetFilter(v *ListTodosRequest_Filter) {
	x.xxx_hidden_Filter = v
}

func (x *ListTodosRequest) SetOrderBy(v []*ListTodosRequest_OrderBy) {
	x.xxx_hidden_OrderBy = &v
}

func (x *ListTodosRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ListTodosRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *ListTodosRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ListTodosRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *ListTodosRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ShowDeleted = false
}

type ListTodosRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The maximum number of todos to return
	// The service may return fewer than this value
	// If unspecified, defaults to 50
	// Maximum value is 1000
	PageSize int32
	// Page token received from a previous ListTodos call
	// Provide this to retrieve the next page
	PageToken string
	// parent
	UserId int64
	// Filter expression for todos
	// Examples: "status=PENDING", "assignee=user123"
	Filter *ListTodosRequest_Filter
	// Field to sort by
	// Examples: "created_at", "due_date", "priority"
	OrderBy []*ListTodosRequest_OrderBy
	// default to false if not set
	ShowDeleted *bool
}

func (b0 ListTodosRequest_builder) Build() *ListTodosRequest {
	m0 := &ListTodosRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PageSize = b.PageSize
	x.xxx_hidden_PageToken = b.PageToken
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_OrderBy = &b.OrderBy
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

// Response message for ListTodos
type ListTodosResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Todos         *[]*Todo               `protobuf:"bytes,1,rep,name=todos,proto3"`
	xxx_hidden_NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3"`
	xxx_hidden_TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		if x.xxx_hidden_Todos != nil {
			return *x.xxx_hidden_Todos
		}
	}
	return nil
}

func (x *ListTodosResponse) GetNextPageToken() string {
	if x != nil {
		return x.xxx_hidden_NextPageToken
	}
	return ""
}

func (x *ListTodosResponse) GetTotalSize() int32 {
	if x != nil {
		return x.xxx_hidden_TotalSize
	}
	return 0
}

func (x *ListTodosResponse) SetTodos(v []*Todo) {
	x.xxx_hidden_Todos = &v
}

func (x *ListTodosResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = v
}

func (x *ListTodosResponse) SetTotalSize(v int32) {
	x.xxx_hidden_TotalSize = v
}

type ListTodosResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The list of todos
	Todos []*Todo
	// Token to retrieve the next page of results
	// Empty if there are no more results
	NextPageToken string
	// Total count of todos matching the filter
	TotalSize int32
}

func (b0 ListTodosResponse_builder) Build() *ListTodosResponse {
	m0 := &ListTodosResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todos = &b.Todos
	x.xxx_hidden_NextPageToken = b.NextPageToken
	x.xxx_hidden_TotalSize = b.TotalSize
	return m0
}

// Request message for UpdateTodo
type UpdateTodoRequest struct {
	state                        protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_Id                int64                                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Title             *string                                `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
	xxx_hidden_Description       *string                                `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
	xxx_hidden_State             Todo_State                             `protobuf:"varint,4,opt,name=state,proto3,enum=monorepo.todo.v1.Todo_State,oneof"`
	xxx_hidden_Priority          Todo_Priority                          `protobuf:"varint,5,opt,name=priority,proto3,enum=monorepo.todo.v1.Todo_Priority,oneof"`
	xxx_hidden_Assignee          int64                                  `protobuf:"varint,6,opt,name=assignee,proto3,oneof"`
	xxx_hidden_DueDate           *date.Date                             `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3,oneof"`
	xxx_hidden_SubTaskOperations *[]*UpdateTodoRequest_SubTaskOperation `protobuf:"bytes,8,rep,name=sub_task_operations,json=subTaskOperations,proto3"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateTodoRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateTodoRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *UpdateTodoRequest) GetState() Todo_State {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return Todo_STATE_UNSPECIFIED
}

func (x *UpdateTodoRequest) GetPriority() Todo_Priority {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Priority
		}
	}
	return Todo_PRIORITY_UNSPECIFIED
}

func (x *UpdateTodoRequest) GetAssignee() int64 {
	if x != nil {
		return x.xxx_hidden_Assignee
	}
	return 0
}

func (x *UpdateTodoRequest) GetDueDate() *date.Date {
	if x != nil {
		return x.xxx_hidden_DueDate
	}
	return nil
}

func (x *UpdateTodoRequest) GetSubTaskOperations() []*UpdateTodoRequest_SubTaskOperation {
	if x != nil {
		if x.xxx_hidden_SubTaskOperations != nil {
			return *x.xxx_hidden_SubTaskOperations
		}
	}
	return nil
}

func (x *UpdateTodoRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *UpdateTodoRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *UpdateTodoRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *UpdateTodoRequest) SetState(v Todo_State) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *UpdateTodoRequest) SetPriority(v Todo_Priority) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *UpdateTodoRequest) SetAssignee(v int64) {
	x.xxx_hidden_Assignee = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *UpdateTodoRequest) SetDueDate(v *date.Date) {
	x.xxx_hidden_DueDate = v
}

func (x *UpdateTodoRequest) SetSubTaskOperations(v []*UpdateTodoRequest_SubTaskOperation) {
	x.xxx_hidden_SubTaskOperations = &v
}

func (x *UpdateTodoRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateTodoRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateTodoRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateTodoRequest) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateTodoRequest) HasAssignee() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UpdateTodoRequest) HasDueDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DueDate != nil
}

func (x *UpdateTodoRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *UpdateTodoRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *UpdateTodoRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = Todo_STATE_UNSPECIFIED
}

func (x *UpdateTodoRequest) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Priority = Todo_PRIORITY_UNSPECIFIED
}

func (x *UpdateTodoRequest) ClearAssignee() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Assignee = 0
}

func (x *UpdateTodoRequest) ClearDueDate() {
	x.xxx_hidden_DueDate = nil
}

type UpdateTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                int64
	Title             *string
	Description       *string
	State             *Todo_State
	Priority          *Todo_Priority
	Assignee          *int64
	DueDate           *date.Date
	SubTaskOperations []*UpdateTodoRequest_SubTaskOperation
}

func (b0 UpdateTodoRequest_builder) Build() *UpdateTodoRequest {
	m0 := &UpdateTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Description = b.Description
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_State = *b.State
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Priority = *b.Priority
	}
	if b.Assignee != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Assignee = *b.Assignee
	}
	x.xxx_hidden_DueDate = b.DueDate
	x.xxx_hidden_SubTaskOperations = &b.SubTaskOperations
	return m0
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteTodoRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteTodoRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteTodoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteTodoRequest_builder) Build() *DeleteTodoRequest {
	m0 := &DeleteTodoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type CreateSubtaskRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSubtaskRequest) Reset() {
	*x = CreateSubtaskRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubtaskRequest) ProtoMessage() {}

func (x *CreateSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSubtaskRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateSubtaskRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

type CreateSubtaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title string
}

func (b0 CreateSubtaskRequest_builder) Build() *CreateSubtaskRequest {
	m0 := &CreateSubtaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	return m0
}

type UpdateSubtaskRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Title       *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateSubtaskRequest) Reset() {
	*x = UpdateSubtaskRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubtaskRequest) ProtoMessage() {}

func (x *UpdateSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSubtaskRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateSubtaskRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateSubtaskRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *UpdateSubtaskRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateSubtaskRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateSubtaskRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

type UpdateSubtaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    int64
	Title *string
}

func (b0 UpdateSubtaskRequest_builder) Build() *UpdateSubtaskRequest {
	m0 := &UpdateSubtaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Title = b.Title
	}
	return m0
}

type DeleteSubtaskRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubtaskRequest) Reset() {
	*x = DeleteSubtaskRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubtaskRequest) ProtoMessage() {}

func (x *DeleteSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSubtaskRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteSubtaskRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteSubtaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteSubtaskRequest_builder) Build() *DeleteSubtaskRequest {
	m0 := &DeleteSubtaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type BatchGetTodosRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ids         []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3"`
	xxx_hidden_ShowDeleted bool                   `protobuf:"varint,2,opt,name=show_deleted,json=showDeleted,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatchGetTodosRequest) Reset() {
	*x = BatchGetTodosRequest{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTodosRequest) ProtoMessage() {}

func (x *BatchGetTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchGetTodosRequest) GetIds() []int64 {
	if x != nil {
		return x.xxx_hidden_Ids
	}
	return nil
}

func (x *BatchGetTodosRequest) GetShowDeleted() bool {
	if x != nil {
		return x.xxx_hidden_ShowDeleted
	}
	return false
}

func (x *BatchGetTodosRequest) SetIds(v []int64) {
	x.xxx_hidden_Ids = v
}

func (x *BatchGetTodosRequest) SetShowDeleted(v bool) {
	x.xxx_hidden_ShowDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *BatchGetTodosRequest) HasShowDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BatchGetTodosRequest) ClearShowDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ShowDeleted = false
}

type BatchGetTodosRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ids []int64
	// default to true if not set
	ShowDeleted *bool
}

func (b0 BatchGetTodosRequest_builder) Build() *BatchGetTodosRequest {
	m0 := &BatchGetTodosRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ids = b.Ids
	if b.ShowDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ShowDeleted = *b.ShowDeleted
	}
	return m0
}

type BatchGetTodosResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Todos *[]*Todo               `protobuf:"bytes,1,rep,name=todos,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchGetTodosResponse) Reset() {
	*x = BatchGetTodosResponse{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTodosResponse) ProtoMessage() {}

func (x *BatchGetTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchGetTodosResponse) GetTodos() []*Todo {
	if x != nil {
		if x.xxx_hidden_Todos != nil {
			return *x.xxx_hidden_Todos
		}
	}
	return nil
}

func (x *BatchGetTodosResponse) SetTodos(v []*Todo) {
	x.xxx_hidden_Todos = &v
}

type BatchGetTodosResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Todos []*Todo
}

func (b0 BatchGetTodosResponse_builder) Build() *BatchGetTodosResponse {
	m0 := &BatchGetTodosResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todos = &b.Todos
	return m0
}

type ListTodosRequest_Filter struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_States     []Todo_State           `protobuf:"varint,1,rep,packed,name=states,proto3,enum=monorepo.todo.v1.Todo_State"`
	xxx_hidden_Priorities []Todo_Priority        `protobuf:"varint,2,rep,packed,name=priorities,proto3,enum=monorepo.todo.v1.Todo_Priority"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListTodosRequest_Filter) Reset() {
	*x = ListTodosRequest_Filter{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest_Filter) ProtoMessage() {}

func (x *ListTodosRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest_Filter) GetStates() []Todo_State {
	if x != nil {
		return x.xxx_hidden_States
	}
	return nil
}

func (x *ListTodosRequest_Filter) GetPriorities() []Todo_Priority {
	if x != nil {
		return x.xxx_hidden_Priorities
	}
	return nil
}

func (x *ListTodosRequest_Filter) SetStates(v []Todo_State) {
	x.xxx_hidden_States = v
}

func (x *ListTodosRequest_Filter) SetPriorities(v []Todo_Priority) {
	x.xxx_hidden_Priorities = v
}

type ListTodosRequest_Filter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	States     []Todo_State
	Priorities []Todo_Priority
}

func (b0 ListTodosRequest_Filter_builder) Build() *ListTodosRequest_Filter {
	m0 := &ListTodosRequest_Filter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_States = b.States
	x.xxx_hidden_Priorities = b.Priorities
	return m0
}

type ListTodosRequest_OrderBy struct {
	state             protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Field  ListTodosRequest_OrderBy_Field `protobuf:"varint,1,opt,name=field,proto3,enum=monorepo.todo.v1.ListTodosRequest_OrderBy_Field"`
	xxx_hidden_IsDesc bool                           `protobuf:"varint,2,opt,name=is_desc,json=isDesc,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListTodosRequest_OrderBy) Reset() {
	*x = ListTodosRequest_OrderBy{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest_OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest_OrderBy) ProtoMessage() {}

func (x *ListTodosRequest_OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTodosRequest_OrderBy) GetField() ListTodosRequest_OrderBy_Field {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return ListTodosRequest_OrderBy_FIELD_UNSPECIFIED
}

func (x *ListTodosRequest_OrderBy) GetIsDesc() bool {
	if x != nil {
		return x.xxx_hidden_IsDesc
	}
	return false
}

func (x *ListTodosRequest_OrderBy) SetField(v ListTodosRequest_OrderBy_Field) {
	x.xxx_hidden_Field = v
}

func (x *ListTodosRequest_OrderBy) SetIsDesc(v bool) {
	x.xxx_hidden_IsDesc = v
}

type ListTodosRequest_OrderBy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field  ListTodosRequest_OrderBy_Field
	IsDesc bool
}

func (b0 ListTodosRequest_OrderBy_builder) Build() *ListTodosRequest_OrderBy {
	m0 := &ListTodosRequest_OrderBy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Field = b.Field
	x.xxx_hidden_IsDesc = b.IsDesc
	return m0
}

type UpdateTodoRequest_SubTaskOperation struct {
	state                protoimpl.MessageState                         `protogen:"opaque.v1"`
	xxx_hidden_Operation isUpdateTodoRequest_SubTaskOperation_Operation `protobuf_oneof:"operation"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTodoRequest_SubTaskOperation) Reset() {
	*x = UpdateTodoRequest_SubTaskOperation{}
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest_SubTaskOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest_SubTaskOperation) ProtoMessage() {}

func (x *UpdateTodoRequest_SubTaskOperation) ProtoReflect() protoreflect.Message {
	mi := &file_monorepo_todo_v1_todo_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateTodoRequest_SubTaskOperation) GetCreate() *CreateSubtaskRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *UpdateTodoRequest_SubTaskOperation) GetUpdate() *UpdateSubtaskRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *UpdateTodoRequest_SubTaskOperation) GetDelete() *DeleteSubtaskRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *UpdateTodoRequest_SubTaskOperation) SetCreate(v *CreateSubtaskRequest) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Create{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) SetUpdate(v *UpdateSubtaskRequest) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Update{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) SetDelete(v *DeleteSubtaskRequest) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Delete{v}
}

func (x *UpdateTodoRequest_SubTaskOperation) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *UpdateTodoRequest_SubTaskOperation) HasCreate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) HasUpdate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) HasDelete() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete)
	return ok
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearCreate() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Create); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearUpdate() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Update); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *UpdateTodoRequest_SubTaskOperation) ClearDelete() {
	if _, ok := x.xxx_hidden_Operation.(*updateTodoRequest_SubTaskOperation_Delete); ok {
		x.xxx_hidden_Operation = nil
	}
}

const UpdateTodoRequest_SubTaskOperation_Operation_not_set_case case_UpdateTodoRequest_SubTaskOperation_Operation = 0
const UpdateTodoRequest_SubTaskOperation_Create_case case_UpdateTodoRequest_SubTaskOperation_Operation = 1
const UpdateTodoRequest_SubTaskOperation_Update_case case_UpdateTodoRequest_SubTaskOperation_Operation = 2
const UpdateTodoRequest_SubTaskOperation_Delete_case case_UpdateTodoRequest_SubTaskOperation_Operation = 3

func (x *UpdateTodoRequest_SubTaskOperation) WhichOperation() case_UpdateTodoRequest_SubTaskOperation_Operation {
	if x == nil {
		return UpdateTodoRequest_SubTaskOperation_Operation_not_set_case
	}
	switch x.xxx_hidden_Operation.(type) {
	case *updateTodoRequest_SubTaskOperation_Create:
		return UpdateTodoRequest_SubTaskOperation_Create_case
	case *updateTodoRequest_SubTaskOperation_Update:
		return UpdateTodoRequest_SubTaskOperation_Update_case
	case *updateTodoRequest_SubTaskOperation_Delete:
		return UpdateTodoRequest_SubTaskOperation_Delete_case
	default:
		return UpdateTodoRequest_SubTaskOperation_Operation_not_set_case
	}
}

type UpdateTodoRequest_SubTaskOperation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Operation:
	Create *CreateSubtaskRequest
	Update *UpdateSubtaskRequest
	Delete *DeleteSubtaskRequest
	// -- end of xxx_hidden_Operation
}

func (b0 UpdateTodoRequest_SubTaskOperation_builder) Build() *UpdateTodoRequest_SubTaskOperation {
	m0 := &UpdateTodoRequest_SubTaskOperation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Create != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Create{b.Create}
	}
	if b.Update != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Update{b.Update}
	}
	if b.Delete != nil {
		x.xxx_hidden_Operation = &updateTodoRequest_SubTaskOperation_Delete{b.Delete}
	}
	return m0
}

type case_UpdateTodoRequest_SubTaskOperation_Operation protoreflect.FieldNumber

func (x case_UpdateTodoRequest_SubTaskOperation_Operation) String() string {
	md := file_monorepo_todo_v1_todo_service_proto_msgTypes[13].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUpdateTodoRequest_SubTaskOperation_Operation interface {
	isUpdateTodoRequest_SubTaskOperation_Operation()
}

type updateTodoRequest_SubTaskOperation_Create struct {
	Create *CreateSubtaskRequest `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type updateTodoRequest_SubTaskOperation_Update struct {
	Update *UpdateSubtaskRequest `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type updateTodoRequest_SubTaskOperation_Delete struct {
	Delete *DeleteSubtaskRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*updateTodoRequest_SubTaskOperation_Create) isUpdateTodoRequest_SubTaskOperation_Operation() {}

func (*updateTodoRequest_SubTaskOperation_Update) isUpdateTodoRequest_SubTaskOperation_Operation() {}

func (*updateTodoRequest_SubTaskOperation_Delete) isUpdateTodoRequest_SubTaskOperation_Operation() {}

var File_monorepo_todo_v1_todo_service_proto protoreflect.FileDescriptor

const file_monorepo_todo_v1_todo_service_proto_rawDesc = "" +
	"\n" +
	"#monorepo/todo/v1/todo_service.proto\x12\x10monorepo.todo.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x16google/type/date.proto\x1a\x1bmonorepo/todo/v1/todo.proto\"\xbe\x03\n" +
	"\x11CreateTodoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.monorepo.todo.v1.Todo.StateH\x01R\x05state\x88\x01\x01\x12@\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1f.monorepo.todo.v1.Todo.PriorityH\x02R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bassignee\x18\x06 \x01(\x03H\x03R\bassignee\x88\x01\x01\x121\n" +
	"\bdue_date\x18\a \x01(\v2\x11.google.type.DateH\x04R\adueDate\x88\x01\x01\x12C\n" +
	"\tsub_tasks\x18\b \x03(\v2&.monorepo.todo.v1.CreateSubtaskRequestR\bsubTasksB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_assigneeB\v\n" +
	"\t_due_date\"Y\n" +
	"\x0eGetTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\fshow_deleted\x18\x02 \x01(\bH\x00R\vshowDeleted\x88\x01\x01B\x0f\n" +
	"\r_show_deleted\"\xf4\x04\n" +
	"\x10ListTodosRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12F\n" +
	"\x06filter\x18\x04 \x01(\v2).monorepo.todo.v1.ListTodosRequest.FilterH\x00R\x06filter\x88\x01\x01\x12E\n" +
	"\border_by\x18\x05 \x03(\v2*.monorepo.todo.v1.ListTodosRequest.OrderByR\aorderBy\x12&\n" +
	"\fshow_deleted\x18\x06 \x01(\bH\x01R\vshowDeleted\x88\x01\x01\x1a\x7f\n" +
	"\x06Filter\x124\n" +
	"\x06states\x18\x01 \x03(\x0e2\x1c.monorepo.todo.v1.Todo.StateR\x06states\x12?\n" +
	"\n" +
	"priorities\x18\x02 \x03(\x0e2\x1f.monorepo.todo.v1.Todo.PriorityR\n" +
	"priorities\x1a\xb6\x01\n" +
	"\aOrderBy\x12F\n" +
	"\x05field\x18\x01 \x01(\x0e20.monorepo.todo.v1.ListTodosRequest.OrderBy.FieldR\x05field\x12\x17\n" +
	"\ais_desc\x18\x02 \x01(\bR\x06isDesc\"J\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x01\x12\f\n" +
	"\bDUE_DATE\x10\x02\x12\f\n" +
	"\bPRIORITY\x10\x03B\t\n" +
	"\a_filterB\x0f\n" +
	"\r_show_deleted\"\x88\x01\n" +
	"\x11ListTodosResponse\x12,\n" +
	"\x05todos\x18\x01 \x03(\v2\x16.monorepo.todo.v1.TodoR\x05todos\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\xcd\x05\n" +
	"\x11UpdateTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.monorepo.todo.v1.Todo.StateH\x02R\x05state\x88\x01\x01\x12@\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1f.monorepo.todo.v1.Todo.PriorityH\x03R\bpriority\x88\x01\x01\x12\x1f\n" +
	"\bassignee\x18\x06 \x01(\x03H\x04R\bassignee\x88\x01\x01\x121\n" +
	"\bdue_date\x18\a \x01(\v2\x11.google.type.DateH\x05R\adueDate\x88\x01\x01\x12d\n" +
	"\x13sub_task_operations\x18\b \x03(\v24.monorepo.todo.v1.UpdateTodoRequest.SubTaskOperationR\x11subTaskOperations\x1a\xe5\x01\n" +
	"\x10SubTaskOperation\x12@\n" +
	"\x06create\x18\x01 \x01(\v2&.monorepo.todo.v1.CreateSubtaskRequestH\x00R\x06create\x12@\n" +
	"\x06update\x18\x02 \x01(\v2&.monorepo.todo.v1.UpdateSubtaskRequestH\x00R\x06update\x12@\n" +
	"\x06delete\x18\x03 \x01(\v2&.monorepo.todo.v1.DeleteSubtaskRequestH\x00R\x06deleteB\v\n" +
	"\toperationB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_stateB\v\n" +
	"\t_priorityB\v\n" +
	"\t_assigneeB\v\n" +
	"\t_due_date\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x14CreateSubtaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"K\n" +
	"\x14UpdateSubtaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title\"&\n" +
	"\x14DeleteSubtaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x14BatchGetTodosRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12&\n" +
	"\fshow_deleted\x18\x02 \x01(\bH\x00R\vshowDeleted\x88\x01\x01B\x0f\n" +
	"\r_show_deleted\"E\n" +
	"\x15BatchGetTodosResponse\x12,\n" +
	"\x05todos\x18\x01 \x03(\v2\x16.monorepo.todo.v1.TodoR\x05todos2\xf7\x03\n" +
	"\vTodoService\x12K\n" +
	"\n" +
	"CreateTodo\x12#.monorepo.todo.v1.CreateTodoRequest\x1a\x16.monorepo.todo.v1.Todo\"\x00\x12E\n" +
	"\aGetTodo\x12 .monorepo.todo.v1.GetTodoRequest\x1a\x16.monorepo.todo.v1.Todo\"\x00\x12V\n" +
	"\tListTodos\x12\".monorepo.todo.v1.ListTodosRequest\x1a#.monorepo.todo.v1.ListTodosResponse\"\x00\x12K\n" +
	"\n" +
	"UpdateTodo\x12#.monorepo.todo.v1.UpdateTodoRequest\x1a\x16.monorepo.todo.v1.Todo\"\x00\x12K\n" +
	"\n" +
	"DeleteTodo\x12#.monorepo.todo.v1.DeleteTodoRequest\x1a\x16.monorepo.todo.v1.Todo\"\x00\x12b\n" +
	"\rBatchGetTodos\x12&.monorepo.todo.v1.BatchGetTodosRequest\x1a'.monorepo.todo.v1.BatchGetTodosResponse\"\x00Bw\n" +
	"\x16monorepo.proto.todo.v1P\x01Z[github.com/yourorg/monorepo/packages/proto-gen-go/monorepo/todo/pkg/monorepo/todo/v1;todov1b\x06proto3"

var file_monorepo_todo_v1_todo_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monorepo_todo_v1_todo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_monorepo_todo_v1_todo_service_proto_goTypes = []any{
	(ListTodosRequest_OrderBy_Field)(0),        // 0: monorepo.todo.v1.ListTodosRequest.OrderBy.Field
	(*CreateTodoRequest)(nil),                  // 1: monorepo.todo.v1.CreateTodoRequest
	(*GetTodoRequest)(nil),                     // 2: monorepo.todo.v1.GetTodoRequest
	(*ListTodosRequest)(nil),                   // 3: monorepo.todo.v1.ListTodosRequest
	(*ListTodosResponse)(nil),                  // 4: monorepo.todo.v1.ListTodosResponse
	(*UpdateTodoRequest)(nil),                  // 5: monorepo.todo.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil),                  // 6: monorepo.todo.v1.DeleteTodoRequest
	(*CreateSubtaskRequest)(nil),               // 7: monorepo.todo.v1.CreateSubtaskRequest
	(*UpdateSubtaskRequest)(nil),               // 8: monorepo.todo.v1.UpdateSubtaskRequest
	(*DeleteSubtaskRequest)(nil),               // 9: monorepo.todo.v1.DeleteSubtaskRequest
	(*BatchGetTodosRequest)(nil),               // 10: monorepo.todo.v1.BatchGetTodosRequest
	(*BatchGetTodosResponse)(nil),              // 11: monorepo.todo.v1.BatchGetTodosResponse
	(*ListTodosRequest_Filter)(nil),            // 12: monorepo.todo.v1.ListTodosRequest.Filter
	(*ListTodosRequest_OrderBy)(nil),           // 13: monorepo.todo.v1.ListTodosRequest.OrderBy
	(*UpdateTodoRequest_SubTaskOperation)(nil), // 14: monorepo.todo.v1.UpdateTodoRequest.SubTaskOperation
	(Todo_State)(0),                            // 15: monorepo.todo.v1.Todo.State
	(Todo_Priority)(0),                         // 16: monorepo.todo.v1.Todo.Priority
	(*date.Date)(nil),                          // 17: google.type.Date
	(*Todo)(nil),                               // 18: monorepo.todo.v1.Todo
}
var file_monorepo_todo_v1_todo_service_proto_depIdxs = []int32{
	15, // 0: monorepo.todo.v1.CreateTodoRequest.state:type_name -> monorepo.todo.v1.Todo.State
	16, // 1: monorepo.todo.v1.CreateTodoRequest.priority:type_name -> monorepo.todo.v1.Todo.Priority
	17, // 2: monorepo.todo.v1.CreateTodoRequest.due_date:type_name -> google.type.Date
	7,  // 3: monorepo.todo.v1.CreateTodoRequest.sub_tasks:type_name -> monorepo.todo.v1.CreateSubtaskRequest
	12, // 4: monorepo.todo.v1.ListTodosRequest.filter:type_name -> monorepo.todo.v1.ListTodosRequest.Filter
	13, // 5: monorepo.todo.v1.ListTodosRequest.order_by:type_name -> monorepo.todo.v1.ListTodosRequest.OrderBy
	18, // 6: monorepo.todo.v1.ListTodosResponse.todos:type_name -> monorepo.todo.v1.Todo
	15, // 7: monorepo.todo.v1.UpdateTodoRequest.state:type_name -> monorepo.todo.v1.Todo.State
	16, // 8: monorepo.todo.v1.UpdateTodoRequest.priority:type_name -> monorepo.todo.v1.Todo.Priority
	17, // 9: monorepo.todo.v1.UpdateTodoRequest.due_date:type_name -> google.type.Date
	14, // 10: monorepo.todo.v1.UpdateTodoRequest.sub_task_operations:type_name -> monorepo.todo.v1.UpdateTodoRequest.SubTaskOperation
	18, // 11: monorepo.todo.v1.BatchGetTodosResponse.todos:type_name -> monorepo.todo.v1.Todo
	15, // 12: monorepo.todo.v1.ListTodosRequest.Filter.states:type_name -> monorepo.todo.v1.Todo.State
	16, // 13: monorepo.todo.v1.ListTodosRequest.Filter.priorities:type_name -> monorepo.todo.v1.Todo.Priority
	0,  // 14: monorepo.todo.v1.ListTodosRequest.OrderBy.field:type_name -> monorepo.todo.v1.ListTodosRequest.OrderBy.Field
	7,  // 15: monorepo.todo.v1.UpdateTodoRequest.SubTaskOperation.create:type_name -> monorepo.todo.v1.CreateSubtaskRequest
	8,  // 16: monorepo.todo.v1.UpdateTodoRequest.SubTaskOperation.update:type_name -> monorepo.todo.v1.UpdateSubtaskRequest
	9,  // 17: monorepo.todo.v1.UpdateTodoRequest.SubTaskOperation.delete:type_name -> monorepo.todo.v1.DeleteSubtaskRequest
	1,  // 18: monorepo.todo.v1.TodoService.CreateTodo:input_type -> monorepo.todo.v1.CreateTodoRequest
	2,  // 19: monorepo.todo.v1.TodoService.GetTodo:input_type -> monorepo.todo.v1.GetTodoRequest
	3,  // 20: monorepo.todo.v1.TodoService.ListTodos:input_type -> monorepo.todo.v1.ListTodosRequest
	5,  // 21: monorepo.todo.v1.TodoService.UpdateTodo:input_type -> monorepo.todo.v1.UpdateTodoRequest
	6,  // 22: monorepo.todo.v1.TodoService.DeleteTodo:input_type -> monorepo.todo.v1.DeleteTodoRequest
	10, // 23: monorepo.todo.v1.TodoService.BatchGetTodos:input_type -> monorepo.todo.v1.BatchGetTodosRequest
	18, // 24: monorepo.todo.v1.TodoService.CreateTodo:output_type -> monorepo.todo.v1.Todo
	18, // 25: monorepo.todo.v1.TodoService.GetTodo:output_type -> monorepo.todo.v1.Todo
	4,  // 26: monorepo.todo.v1.TodoService.ListTodos:output_type -> monorepo.todo.v1.ListTodosResponse
	18, // 27: monorepo.todo.v1.TodoService.UpdateTodo:output_type -> monorepo.todo.v1.Todo
	18, // 28: monorepo.todo.v1.TodoService.DeleteTodo:output_type -> monorepo.todo.v1.Todo
	11, // 29: monorepo.todo.v1.TodoService.BatchGetTodos:output_type -> monorepo.todo.v1.BatchGetTodosResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_monorepo_todo_v1_todo_service_proto_init() }
func file_monorepo_todo_v1_todo_service_proto_init() {
	if File_monorepo_todo_v1_todo_service_proto != nil {
		return
	}
	file_monorepo_todo_v1_todo_proto_init()
	file_monorepo_todo_v1_todo_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_monorepo_todo_v1_todo_service_proto_msgTypes[13].OneofWrappers = []any{
		(*updateTodoRequest_SubTaskOperation_Create)(nil),
		(*updateTodoRequest_SubTaskOperation_Update)(nil),
		(*updateTodoRequest_SubTaskOperation_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monorepo_todo_v1_todo_service_proto_rawDesc), len(file_monorepo_todo_v1_todo_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monorepo_todo_v1_todo_service_proto_goTypes,
		DependencyIndexes: file_monorepo_todo_v1_todo_service_proto_depIdxs,
		EnumInfos:         file_monorepo_todo_v1_todo_service_proto_enumTypes,
		MessageInfos:      file_monorepo_todo_v1_todo_service_proto_msgTypes,
	}.Build()
	File_monorepo_todo_v1_todo_service_proto = out.File
	file_monorepo_todo_v1_todo_service_proto_goTypes = nil
	file_monorepo_todo_v1_todo_service_proto_depIdxs = nil
}
