// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo_service.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

/**
 * Protobuf type {@code todo.v1.BatchGetTodosRequest}
 */
@com.google.protobuf.Generated
public final class BatchGetTodosRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:todo.v1.BatchGetTodosRequest)
    BatchGetTodosRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "BatchGetTodosRequest");
  }
  // Use BatchGetTodosRequest.newBuilder() to construct.
  private BatchGetTodosRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchGetTodosRequest() {
    ids_ = emptyLongList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return monorepo.proto.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_BatchGetTodosRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return monorepo.proto.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_BatchGetTodosRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            monorepo.proto.todo.v1.BatchGetTodosRequest.class, monorepo.proto.todo.v1.BatchGetTodosRequest.Builder.class);
  }

  private int bitField0_;
  public static final int IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList ids_ =
      emptyLongList();
  /**
   * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
   * @return A list containing the ids.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getIdsList() {
    return ids_;
  }
  /**
   * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
   * @return The count of ids.
   */
  public int getIdsCount() {
    return ids_.size();
  }
  /**
   * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  public long getIds(int index) {
    return ids_.getLong(index);
  }
  private int idsMemoizedSerializedSize = -1;

  public static final int SHOW_DELETED_FIELD_NUMBER = 2;
  private boolean showDeleted_ = false;
  /**
   * <pre>
   * default to true if not set
   * </pre>
   *
   * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
   * @return Whether the showDeleted field is set.
   */
  @java.lang.Override
  public boolean hasShowDeleted() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * default to true if not set
   * </pre>
   *
   * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
   * @return The showDeleted.
   */
  @java.lang.Override
  public boolean getShowDeleted() {
    return showDeleted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getIdsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(idsMemoizedSerializedSize);
    }
    for (int i = 0; i < ids_.size(); i++) {
      output.writeInt64NoTag(ids_.getLong(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(2, showDeleted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < ids_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(ids_.getLong(i));
      }
      size += dataSize;
      if (!getIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      idsMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, showDeleted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof monorepo.proto.todo.v1.BatchGetTodosRequest)) {
      return super.equals(obj);
    }
    monorepo.proto.todo.v1.BatchGetTodosRequest other = (monorepo.proto.todo.v1.BatchGetTodosRequest) obj;

    if (!getIdsList()
        .equals(other.getIdsList())) return false;
    if (hasShowDeleted() != other.hasShowDeleted()) return false;
    if (hasShowDeleted()) {
      if (getShowDeleted()
          != other.getShowDeleted()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdsCount() > 0) {
      hash = (37 * hash) + IDS_FIELD_NUMBER;
      hash = (53 * hash) + getIdsList().hashCode();
    }
    if (hasShowDeleted()) {
      hash = (37 * hash) + SHOW_DELETED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getShowDeleted());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static monorepo.proto.todo.v1.BatchGetTodosRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(monorepo.proto.todo.v1.BatchGetTodosRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code todo.v1.BatchGetTodosRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.v1.BatchGetTodosRequest)
      monorepo.proto.todo.v1.BatchGetTodosRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monorepo.proto.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_BatchGetTodosRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monorepo.proto.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_BatchGetTodosRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monorepo.proto.todo.v1.BatchGetTodosRequest.class, monorepo.proto.todo.v1.BatchGetTodosRequest.Builder.class);
    }

    // Construct using monorepo.proto.todo.v1.BatchGetTodosRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ids_ = emptyLongList();
      showDeleted_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return monorepo.proto.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_BatchGetTodosRequest_descriptor;
    }

    @java.lang.Override
    public monorepo.proto.todo.v1.BatchGetTodosRequest getDefaultInstanceForType() {
      return monorepo.proto.todo.v1.BatchGetTodosRequest.getDefaultInstance();
    }

    @java.lang.Override
    public monorepo.proto.todo.v1.BatchGetTodosRequest build() {
      monorepo.proto.todo.v1.BatchGetTodosRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public monorepo.proto.todo.v1.BatchGetTodosRequest buildPartial() {
      monorepo.proto.todo.v1.BatchGetTodosRequest result = new monorepo.proto.todo.v1.BatchGetTodosRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(monorepo.proto.todo.v1.BatchGetTodosRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        ids_.makeImmutable();
        result.ids_ = ids_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.showDeleted_ = showDeleted_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof monorepo.proto.todo.v1.BatchGetTodosRequest) {
        return mergeFrom((monorepo.proto.todo.v1.BatchGetTodosRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(monorepo.proto.todo.v1.BatchGetTodosRequest other) {
      if (other == monorepo.proto.todo.v1.BatchGetTodosRequest.getDefaultInstance()) return this;
      if (!other.ids_.isEmpty()) {
        if (ids_.isEmpty()) {
          ids_ = other.ids_;
          ids_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureIdsIsMutable();
          ids_.addAll(other.ids_);
        }
        onChanged();
      }
      if (other.hasShowDeleted()) {
        setShowDeleted(other.getShowDeleted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureIdsIsMutable();
              ids_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                ids_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              showDeleted_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList ids_ = emptyLongList();
    private void ensureIdsIsMutable() {
      if (!ids_.isModifiable()) {
        ids_ = makeMutableCopy(ids_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @return A list containing the ids.
     */
    public java.util.List<java.lang.Long>
        getIdsList() {
      ids_.makeImmutable();
      return ids_;
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @return The count of ids.
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    public long getIds(int index) {
      return ids_.getLong(index);
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @param index The index to set the value at.
     * @param value The ids to set.
     * @return This builder for chaining.
     */
    public Builder setIds(
        int index, long value) {

      ensureIdsIsMutable();
      ids_.setLong(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @param value The ids to add.
     * @return This builder for chaining.
     */
    public Builder addIds(long value) {

      ensureIdsIsMutable();
      ids_.addLong(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @param values The ids to add.
     * @return This builder for chaining.
     */
    public Builder addAllIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ids_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 ids = 1 [json_name = "ids"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIds() {
      ids_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private boolean showDeleted_ ;
    /**
     * <pre>
     * default to true if not set
     * </pre>
     *
     * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
     * @return Whether the showDeleted field is set.
     */
    @java.lang.Override
    public boolean hasShowDeleted() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * default to true if not set
     * </pre>
     *
     * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
     * @return The showDeleted.
     */
    @java.lang.Override
    public boolean getShowDeleted() {
      return showDeleted_;
    }
    /**
     * <pre>
     * default to true if not set
     * </pre>
     *
     * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
     * @param value The showDeleted to set.
     * @return This builder for chaining.
     */
    public Builder setShowDeleted(boolean value) {

      showDeleted_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * default to true if not set
     * </pre>
     *
     * <code>optional bool show_deleted = 2 [json_name = "showDeleted"];</code>
     * @return This builder for chaining.
     */
    public Builder clearShowDeleted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      showDeleted_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:todo.v1.BatchGetTodosRequest)
  }

  // @@protoc_insertion_point(class_scope:todo.v1.BatchGetTodosRequest)
  private static final monorepo.proto.todo.v1.BatchGetTodosRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new monorepo.proto.todo.v1.BatchGetTodosRequest();
  }

  public static monorepo.proto.todo.v1.BatchGetTodosRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchGetTodosRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchGetTodosRequest>() {
    @java.lang.Override
    public BatchGetTodosRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchGetTodosRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchGetTodosRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public monorepo.proto.todo.v1.BatchGetTodosRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

