// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo_service.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public interface BatchGetTodosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.BatchGetTodosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The list of todos
   * Todos are returned in the same order as requested
   * If a todo is not found, it will not be included in the response
   * </pre>
   *
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<monorepo.proto.todo.v1.Todo> 
      getTodosList();
  /**
   * <pre>
   * The list of todos
   * Todos are returned in the same order as requested
   * If a todo is not found, it will not be included in the response
   * </pre>
   *
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  monorepo.proto.todo.v1.Todo getTodos(int index);
  /**
   * <pre>
   * The list of todos
   * Todos are returned in the same order as requested
   * If a todo is not found, it will not be included in the response
   * </pre>
   *
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  int getTodosCount();
  /**
   * <pre>
   * The list of todos
   * Todos are returned in the same order as requested
   * If a todo is not found, it will not be included in the response
   * </pre>
   *
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<? extends monorepo.proto.todo.v1.TodoOrBuilder> 
      getTodosOrBuilderList();
  /**
   * <pre>
   * The list of todos
   * Todos are returned in the same order as requested
   * If a todo is not found, it will not be included in the response
   * </pre>
   *
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  monorepo.proto.todo.v1.TodoOrBuilder getTodosOrBuilder(
      int index);
}
