// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public interface TodoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.Todo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the todo
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier for the todo
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * User ID - owner/tenant of this todo
   * </pre>
   *
   * <code>string user_id = 2 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * User ID - owner/tenant of this todo
   * </pre>
   *
   * <code>string user_id = 2 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Title of the todo
   * </pre>
   *
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Title of the todo
   * </pre>
   *
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Detailed description of the todo
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Detailed description of the todo
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Status of the todo
   * </pre>
   *
   * <code>.todo.v1.TodoStatus status = 5 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Status of the todo
   * </pre>
   *
   * <code>.todo.v1.TodoStatus status = 5 [json_name = "status"];</code>
   * @return The status.
   */
  monorepo.proto.todo.v1.TodoStatus getStatus();

  /**
   * <pre>
   * Priority level of the todo
   * </pre>
   *
   * <code>.todo.v1.Priority priority = 6 [json_name = "priority"];</code>
   * @return The enum numeric value on the wire for priority.
   */
  int getPriorityValue();
  /**
   * <pre>
   * Priority level of the todo
   * </pre>
   *
   * <code>.todo.v1.Priority priority = 6 [json_name = "priority"];</code>
   * @return The priority.
   */
  monorepo.proto.todo.v1.Priority getPriority();

  /**
   * <pre>
   * User ID of the assignee
   * </pre>
   *
   * <code>string assignee = 7 [json_name = "assignee"];</code>
   * @return The assignee.
   */
  java.lang.String getAssignee();
  /**
   * <pre>
   * User ID of the assignee
   * </pre>
   *
   * <code>string assignee = 7 [json_name = "assignee"];</code>
   * @return The bytes for assignee.
   */
  com.google.protobuf.ByteString
      getAssigneeBytes();

  /**
   * <pre>
   * Due date in Unix timestamp (seconds)
   * </pre>
   *
   * <code>int64 due_date = 8 [json_name = "dueDate"];</code>
   * @return The dueDate.
   */
  long getDueDate();

  /**
   * <pre>
   * Creation timestamp in Unix timestamp (seconds)
   * </pre>
   *
   * <code>int64 created_at = 9 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * Last update timestamp in Unix timestamp (seconds)
   * </pre>
   *
   * <code>int64 updated_at = 10 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();
}
