// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

/**
 * <pre>
 * TodoStatus represents the status of a todo item
 * </pre>
 *
 * Protobuf enum {@code todo.v1.TodoStatus}
 */
@com.google.protobuf.Generated
public enum TodoStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TODO_STATUS_UNSPECIFIED = 0;</code>
   */
  TODO_STATUS_UNSPECIFIED(0),
  /**
   * <code>TODO_STATUS_PENDING = 1;</code>
   */
  TODO_STATUS_PENDING(1),
  /**
   * <code>TODO_STATUS_COMPLETED = 2;</code>
   */
  TODO_STATUS_COMPLETED(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "TodoStatus");
  }
  /**
   * <code>TODO_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int TODO_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>TODO_STATUS_PENDING = 1;</code>
   */
  public static final int TODO_STATUS_PENDING_VALUE = 1;
  /**
   * <code>TODO_STATUS_COMPLETED = 2;</code>
   */
  public static final int TODO_STATUS_COMPLETED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TodoStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TodoStatus forNumber(int value) {
    switch (value) {
      case 0: return TODO_STATUS_UNSPECIFIED;
      case 1: return TODO_STATUS_PENDING;
      case 2: return TODO_STATUS_COMPLETED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TodoStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TodoStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TodoStatus>() {
          public TodoStatus findValueByNumber(int number) {
            return TodoStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return monorepo.proto.todo.v1.TodoOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final TodoStatus[] VALUES = values();

  public static TodoStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TodoStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:todo.v1.TodoStatus)
}

