// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public interface TodoModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.TodoModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.todo.v1.TodoModel.Todo todo = 1 [json_name = "todo"];</code>
   * @return Whether the todo field is set.
   */
  boolean hasTodo();
  /**
   * <code>.todo.v1.TodoModel.Todo todo = 1 [json_name = "todo"];</code>
   * @return The todo.
   */
  monorepo.proto.todo.v1.TodoModel.Todo getTodo();
  /**
   * <code>.todo.v1.TodoModel.Todo todo = 1 [json_name = "todo"];</code>
   */
  monorepo.proto.todo.v1.TodoModel.TodoOrBuilder getTodoOrBuilder();

  /**
   * <code>repeated .todo.v1.TodoModel.SubTask sub_tasks = 3 [json_name = "subTasks"];</code>
   */
  java.util.List<monorepo.proto.todo.v1.TodoModel.SubTask> 
      getSubTasksList();
  /**
   * <code>repeated .todo.v1.TodoModel.SubTask sub_tasks = 3 [json_name = "subTasks"];</code>
   */
  monorepo.proto.todo.v1.TodoModel.SubTask getSubTasks(int index);
  /**
   * <code>repeated .todo.v1.TodoModel.SubTask sub_tasks = 3 [json_name = "subTasks"];</code>
   */
  int getSubTasksCount();
  /**
   * <code>repeated .todo.v1.TodoModel.SubTask sub_tasks = 3 [json_name = "subTasks"];</code>
   */
  java.util.List<? extends monorepo.proto.todo.v1.TodoModel.SubTaskOrBuilder> 
      getSubTasksOrBuilderList();
  /**
   * <code>repeated .todo.v1.TodoModel.SubTask sub_tasks = 3 [json_name = "subTasks"];</code>
   */
  monorepo.proto.todo.v1.TodoModel.SubTaskOrBuilder getSubTasksOrBuilder(
      int index);
}
