// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo/v1/todo_service.proto
// Protobuf Java Version: 4.33.1

package monorepo.proto.todo.v1;

@com.google.protobuf.Generated
public interface UpdateTodoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.UpdateTodoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.todo.v1.UpdateTodoRequest.Todo todo = 1 [json_name = "todo"];</code>
   * @return Whether the todo field is set.
   */
  boolean hasTodo();
  /**
   * <code>.todo.v1.UpdateTodoRequest.Todo todo = 1 [json_name = "todo"];</code>
   * @return The todo.
   */
  monorepo.proto.todo.v1.UpdateTodoRequest.Todo getTodo();
  /**
   * <code>.todo.v1.UpdateTodoRequest.Todo todo = 1 [json_name = "todo"];</code>
   */
  monorepo.proto.todo.v1.UpdateTodoRequest.TodoOrBuilder getTodoOrBuilder();

  /**
   * <code>repeated .todo.v1.UpdateTodoRequest.SubTaskOperation sub_task_operations = 2 [json_name = "subTaskOperations"];</code>
   */
  java.util.List<monorepo.proto.todo.v1.UpdateTodoRequest.SubTaskOperation> 
      getSubTaskOperationsList();
  /**
   * <code>repeated .todo.v1.UpdateTodoRequest.SubTaskOperation sub_task_operations = 2 [json_name = "subTaskOperations"];</code>
   */
  monorepo.proto.todo.v1.UpdateTodoRequest.SubTaskOperation getSubTaskOperations(int index);
  /**
   * <code>repeated .todo.v1.UpdateTodoRequest.SubTaskOperation sub_task_operations = 2 [json_name = "subTaskOperations"];</code>
   */
  int getSubTaskOperationsCount();
  /**
   * <code>repeated .todo.v1.UpdateTodoRequest.SubTaskOperation sub_task_operations = 2 [json_name = "subTaskOperations"];</code>
   */
  java.util.List<? extends monorepo.proto.todo.v1.UpdateTodoRequest.SubTaskOperationOrBuilder> 
      getSubTaskOperationsOrBuilderList();
  /**
   * <code>repeated .todo.v1.UpdateTodoRequest.SubTaskOperation sub_task_operations = 2 [json_name = "subTaskOperations"];</code>
   */
  monorepo.proto.todo.v1.UpdateTodoRequest.SubTaskOperationOrBuilder getSubTaskOperationsOrBuilder(
      int index);
}
